const questionCategories = [
  {
    "id": "fiesta_noche",
    "name": "Fiesta y noche",
    "emoji": "🎉",
    "questions": [
      "¿Quién pediría una última copa con la dignidad ya en modo avión?",
      "¿Quién acabaría siendo amigo íntimo del camarero antes de pagar la primera ronda?",
      "¿Quién bailaría como si estuviera cerrando el festival principal?",
      "¿Quién perdería la chaqueta y ganaría una leyenda urbana?",
      "¿Quién juraría que se va pronto y terminaría viendo amanecer?",
      "¿Quién haría un brindis tan intenso que daría miedo y ternura a la vez?",
      "¿Quién convencería al grupo para entrar en el peor sitio de la noche?",
      "¿Quién se subiría a cantar sin saberse la letra ni sentir vergüenza?",
      "¿Quién convertiría una cena tranquila en una investigación policial al día siguiente?",
      "¿Quién hablaría con desconocidos como si fueran primos segundos?",
      "¿Quién pediría al DJ una canción que nadie más quería escuchar?",
      "¿Quién sería el primero en gritar 'esta es la mía' cinco canciones seguidas?",
      "¿Quién acabaría con purpurina encima sin haberla tocado nunca?",
      "¿Quién haría de relaciones públicas de una fiesta en la que no conoce a nadie?",
      "¿Quién organizaría un after en una casa que no es suya?",
      "¿Quién se tomaría demasiado en serio elegir el bar siguiente?",
      "¿Quién pediría comida de madrugada como si fuera una operación de rescate?",
      "¿Quién sería capaz de perderse dentro del mismo local?",
      "¿Quién saldría en todas las fotos con cara de haber visto el futuro?",
      "¿Quién diría 'solo una' y provocaría el desastre económico del grupo?",
      "¿Quién improvisaría una coreografía que nadie pidió pero todos recordarían?",
      "¿Quién haría una amistad de baño que dura exactamente siete minutos?",
      "¿Quién convertiría una canción vieja en himno nacional de la noche?",
      "¿Quién llegaría a casa con objetos que no sabe de dónde han salido?",
      "¿Quién sería el encargado involuntario de los vídeos vergonzosos?",
      "¿Quién negociaría una entrada gratis con argumentos absurdos?",
      "¿Quién se emocionaría con una balada a las tres de la mañana?",
      "¿Quién acabaría dando consejos vitales a alguien que acaba de conocer?",
      "¿Quién sería capaz de declarar que 'esta noche ha cambiado mi vida'?",
      "¿Quién tendría la resaca moral más larga que la física?",
      "¿Quién propondría jugar al 'verdad o reto' y luego se arrepentiría?",
      "¿Quién desaparecería veinte minutos y volvería con amigos nuevos?",
      "¿Quién se empeñaría en subirse a la cabina del DJ?",
      "¿Quién acabaría la noche llorando de risa en el suelo de la cocina?",
      "¿Quién sería el primero en sacarse la camiseta sin motivo?",
      "¿Quién organizaría una quedada previa que acaba siendo el plan principal?",
      "¿Quién se dormiría en el sofá de un desconocido?",
      "¿Quién tendría más probabilidades de perderse el último transporte?",
      "¿Quién acabaría compartiendo un secreto íntimo con el grupo de fumadores?",
      "¿Quién se empeñaría en que suene 'una más' a las seis de la mañana?"
    ]
  },
  {
    "id": "salseo_drama",
    "name": "Salseo y drama",
    "emoji": "🍿",
    "questions": [
      "¿Quién descubriría un drama solo mirando quién vio una historia?",
      "¿Quién pediría contexto y acabaría sabiendo demasiado?",
      "¿Quién guardaría capturas 'por si acaso' como si fueran documentos secretos?",
      "¿Quién diría que no quiere líos mientras aviva el incendio?",
      "¿Quién sería el primero en soltar 'yo ya lo sabía'?",
      "¿Quién montaría una teoría con tres emojis y una hora de conexión?",
      "¿Quién se enteraría de todo sin preguntar nada directamente?",
      "¿Quién contaría un rumor empezando por 'no debería decir esto'?",
      "¿Quién sería capaz de unir dos bandos solo para tener más información?",
      "¿Quién fingiría sorpresa ante un drama que lleva siguiendo semanas?",
      "¿Quién tendría más datos que los protagonistas del conflicto?",
      "¿Quién crearía un grupo paralelo para comentar el grupo principal?",
      "¿Quién sería el juez más despiadado en un debate tonto?",
      "¿Quién se pondría neutral y caería mal a todos?",
      "¿Quién acabaría mediando y empeorándolo sin querer?",
      "¿Quién usaría un 'jajaja' para esconder una bomba emocional?",
      "¿Quién haría una reconstrucción de los hechos con línea temporal?",
      "¿Quién sería el detective del amor ajeno?",
      "¿Quién perdonaría el drama pero no olvidaría ni una coma?",
      "¿Quién tendría el archivo mental más peligroso del grupo?",
      "¿Quién preguntaría '¿pero qué ha pasado?' sabiendo perfectamente qué pasó?",
      "¿Quién provocaría un silencio incómodo con una frase demasiado precisa?",
      "¿Quién hablaría de paz mientras disfruta del caos?",
      "¿Quién saldría inocente de todos los líos aunque siempre esté cerca?",
      "¿Quién sería capaz de citar mensajes antiguos como prueba judicial?",
      "¿Quién haría de abogado defensor del peor argumento?",
      "¿Quién convertiría una tontería en temporada completa de serie?",
      "¿Quién se ofendería por algo que nadie había dicho?",
      "¿Quién tendría más papeletas de decir 'yo no me meto' justo antes de meterse?",
      "¿Quién dejaría un visto que duele más que una declaración de guerra?",
      "¿Quién revisaría los 'me gusta' antiguos de alguien para sacar conclusiones?",
      "¿Quién haría una encuesta anónima para saber la opinión real del grupo?",
      "¿Quién sería capaz de fingir una reconciliación para obtener más información?",
      "¿Quién guardaría silencio en una discusión y luego soltaría la bomba final?",
      "¿Quién tendría un ranking no oficial de dramas históricos del grupo?",
      "¿Quién se emocionaría cuando aparece 'alguien está escribiendo...'?",
      "¿Quién preguntaría '¿y eso qué significa?' para que repitan el chisme?",
      "¿Quién sería el primero en compartir un chisme con la persona aludida?",
      "¿Quién usaría el 'modo avión' estratégicamente para generar suspense?",
      "¿Quién tendría más capturas de conversaciones que fotos personales?"
    ]
  },
  {
    "id": "picante_suave",
    "name": "Picante suave",
    "emoji": "🌶️",
    "questions": [
      "¿Quién ligaría usando una frase que debería estar prohibida por mal gusto?",
      "¿Quién se enamoraría de alguien solo por cómo pide una bebida?",
      "¿Quién tendría más peligro con confianza y dos halagos?",
      "¿Quién confundiría educación básica con señales clarísimas?",
      "¿Quién escribiría un mensaje atrevido y luego tiraría el móvil al sofá?",
      "¿Quién sería el primero en decir 'yo nunca haría eso' y hacerlo?",
      "¿Quién se pondría rojo con un cumplido inocente?",
      "¿Quién tendría un crush secreto más evidente que un cartel luminoso?",
      "¿Quién convertiría un saludo en una historia romántica de tres actos?",
      "¿Quién flirtearía mejor sin darse cuenta?",
      "¿Quién se vendría arriba respondiendo una historia?",
      "¿Quién miraría el móvil cada diez segundos esperando respuesta?",
      "¿Quién tendría más probabilidades de mandar un mensaje y arrepentirse al instante?",
      "¿Quién sería capaz de pedir consejo para ligar y hacer exactamente lo contrario?",
      "¿Quién haría una playlist para alguien que apenas conoce?",
      "¿Quién sería el más dramático por un 'ok'?",
      "¿Quién tendría más química con la persona más inconveniente?",
      "¿Quién intentaría hacerse el interesante y parecería perdido?",
      "¿Quién se inventaría una excusa absurda para volver a hablar con alguien?",
      "¿Quién sería más peligroso en una boda con barra libre?",
      "¿Quién se acordaría durante años de una mirada de tres segundos?",
      "¿Quién usaría demasiados emojis para parecer casual?",
      "¿Quién acabaría gustándole alguien solo porque le hace reír?",
      "¿Quién sería capaz de organizar un plan entero solo para coincidir con alguien?",
      "¿Quién diría que no busca nada y tendría un discurso preparado?",
      "¿Quién caería antes en un 'tenemos que vernos'?",
      "¿Quién tendría la conversación más inocente con más tensión del mundo?",
      "¿Quién sería el peor disimulando que alguien le gusta?",
      "¿Quién convertiría un match en una investigación de antecedentes?",
      "¿Quién sería el rey o reina del casi algo?",
      "¿Quién mandaría un mensaje borrado estratégicamente para crear intriga?",
      "¿Quién guardaría una foto de perfil antigua de alguien como recuerdo?",
      "¿Quién analizaría los tiempos de respuesta como si fuera una señal divina?",
      "¿Quién se inventaría un 'yo creo que le gusto' con una sola evidencia?",
      "¿Quién sería el primero en declararse bajo los efectos del alcohol?",
      "¿Quién tendría un 'casi algo' con alguien del grupo y lo negaría todo?",
      "¿Quién haría una carta astral de su crush para ver si son compatibles?",
      "¿Quién se obsesionaría con el ex de alguien solo por morbo?",
      "¿Quién ligaría con la persona más inapropiada en la cena de empresa?",
      "¿Quién confundiría amabilidad con coqueteo de forma sistemática?"
    ]
  },
  {
    "id": "amistad_traiciones",
    "name": "Amistad y traiciones pequeñas",
    "emoji": "🤝",
    "questions": [
      "¿Quién vendería al grupo por un postre gratis?",
      "¿Quién defendería a un amigo aunque las pruebas sean humillantes?",
      "¿Quién sería el primero en abandonar un plan cuando empieza a llover?",
      "¿Quién diría 'yo te acompaño' y luego intentaría escaparse?",
      "¿Quién guardaría el secreto más absurdo durante años?",
      "¿Quién contaría una anécdota exagerando hasta cambiar el género de la historia?",
      "¿Quién sería capaz de organizar una intervención por una tontería?",
      "¿Quién tiene más pinta de crear un grupo de WhatsApp innecesario?",
      "¿Quién llegaría tarde incluso si la quedada es debajo de su casa?",
      "¿Quién se apuntaría a un plan sin haber leído ni fecha ni precio?",
      "¿Quién sería el amigo que aparece solo cuando hay comida?",
      "¿Quién pediría perdón con memes?",
      "¿Quién haría un regalo horrible pero con muchísimo amor?",
      "¿Quién se pondría sentimental en una despedida de diez minutos?",
      "¿Quién sería el primero en montar una sorpresa y delatarla sin querer?",
      "¿Quién tiene más cara de saber algo y no poder decirlo?",
      "¿Quién se convertiría en representante oficial del grupo sin votación?",
      "¿Quién traería a una persona nueva y no explicaría de dónde sale?",
      "¿Quién tendría más posibilidades de olvidar que había quedado?",
      "¿Quién sería capaz de hacer de chófer y luego quejarse todo el camino?",
      "¿Quién enviaría un audio de cuatro minutos para decir 'vale'?",
      "¿Quién necesitaría un croquis para entender el drama del grupo?",
      "¿Quién sería el más fiel en una pelea absurda?",
      "¿Quién haría de terapeuta gratis y acabaría agotado?",
      "¿Quién pondría paz con una frase que suena a amenaza?",
      "¿Quién tendría más memes guardados de los demás?",
      "¿Quién sería el primero en proponer un viaje y el último en pagar la reserva?",
      "¿Quién se tomaría una broma demasiado personal?",
      "¿Quién tendría más probabilidades de reconciliar a dos enemigos por cansancio?",
      "¿Quién sería el más querido y el más criticado en la misma noche?",
      "¿Quién usaría el 'yo te lo dije' como deporte?",
      "¿Quién haría un ranking de prioridades donde sus amigos salen perdiendo?",
      "¿Quién se olvidaría de avisar de un cambio de plan y llegaría tarde a propósito?",
      "¿Quién se apuntaría a una cena y cancelaría por algo mejor?",
      "¿Quién tendría más probabilidades de usar la amistad para que le ayuden a mudarse?",
      "¿Quién se enfadaría por un comentario y lo vengaría semanas después?",
      "¿Quién fingiría no tener saldo para no pagar algo?",
      "¿Quién organizaría una cena y cobraría de más por 'gastos de gestión'?",
      "¿Quién sería el amigo que desaparece cuando hay que ayudar y aparece cuando hay fiesta?",
      "¿Quién contaría una historia humillante de un amigo como si fuera chiste propio?"
    ]
  },
  {
    "id": "redes_tecnologia",
    "name": "Redes, móvil e IA",
    "emoji": "📱",
    "questions": [
      "¿Quién subiría una historia y la borraría cuando ya la vio todo el mundo?",
      "¿Quién tendría el historial de búsqueda más difícil de defender?",
      "¿Quién usaría IA para escribir una disculpa demasiado perfecta?",
      "¿Quién respondería tres días tarde como si nada hubiera pasado?",
      "¿Quién mandaría una captura al chat equivocado y empezaría una crisis?",
      "¿Quién tendría 83 pestañas abiertas y ninguna útil?",
      "¿Quién caería antes en una oferta falsa con envío gratis?",
      "¿Quién grabaría un tutorial de algo que no sabe hacer?",
      "¿Quién pondría una contraseña tan obvia que da pena?",
      "¿Quién tendría el móvil destrozado pero diría que va perfecto?",
      "¿Quién se pondría nervioso al 19% de batería?",
      "¿Quién sería influencer por accidente y se lo creería en dos días?",
      "¿Quién discutiría con el asistente de voz?",
      "¿Quién mandaría un sticker devastador en una conversación seria?",
      "¿Quién haría una foto a la comida antes de saludar?",
      "¿Quién sería capaz de hacer doomscrolling en mitad de una película?",
      "¿Quién tendría más aplicaciones que nunca ha abierto?",
      "¿Quién se compraría un gadget raro y lo defendería como revolución mundial?",
      "¿Quién preguntaría algo que Google resuelve en ocho segundos?",
      "¿Quién se haría viral por una caída, una frase o una mala decisión?",
      "¿Quién tendría más notas en el móvil con ideas imposibles?",
      "¿Quién leería una conversación antigua como quien revisa pruebas judiciales?",
      "¿Quién sería el primero en probar una red social nueva y abandonarla al día siguiente?",
      "¿Quién cambiaría de foto de perfil por una crisis existencial leve?",
      "¿Quién caería en una discusión de comentarios sabiendo que no sirve de nada?",
      "¿Quién tendría el grupo silenciado y aun así se enteraría de todo?",
      "¿Quién perdería media hora eligiendo un emoji?",
      "¿Quién usaría ChatGPT para ganar una discusión familiar?",
      "¿Quién escribiría un mensaje larguísimo y acabaría mandando solo 'ok'?",
      "¿Quién tendría la galería llena de memes, tickets y fotos borrosas?",
      "¿Quién se pondría a grabar un vídeo en mitad de una discusión?",
      "¿Quién tendría un filtro de belleza activado hasta para videollamadas de trabajo?",
      "¿Quién sería capaz de discutir con un chatbot y enfadarse de verdad?",
      "¿Quién se crearía un perfil falso para espiar a alguien?",
      "¿Quién publicaría una indirecta clarísima y diría que no es para nadie?",
      "¿Quién revisaría los 'seguidores' de su ex a las 3 de la mañana?",
      "¿Quién usaría el WhatsApp web y se olvidaría de cerrar sesión?",
      "¿Quién tendría un grupo de chat para cotillear sobre otro grupo?",
      "¿Quién contestaría al grupo equivocado con un mensaje comprometedor?",
      "¿Quién se sabría de memoria la letra de una canción solo por los memes?"
    ]
  },
  {
    "id": "trabajo_oficina",
    "name": "Trabajo y oficina",
    "emoji": "💼",
    "questions": [
      "¿Quién sobreviviría a una reunión eterna con cara de estar entendiendo?",
      "¿Quién enviaría un correo demasiado formal para pedir un boli?",
      "¿Quién sería jefe por accidente y lo disfrutaría demasiado?",
      "¿Quién se ofrecería voluntario y se arrepentiría antes de acabar la frase?",
      "¿Quién haría una presentación con más efectos que contenido?",
      "¿Quién llegaría tarde con una excusa cinematográfica?",
      "¿Quién fingiría entender una explicación técnica hasta el final?",
      "¿Quién convertiría una pausa de café en una ruta turística?",
      "¿Quién pondría nombres épicos a tareas aburridas?",
      "¿Quién se tomaría demasiado en serio un team building?",
      "¿Quién sería incapaz de decir que no a un favor?",
      "¿Quién dejaría todo perfecto cinco minutos antes de entregar?",
      "¿Quién convertiría una tarea simple en una tesis doctoral?",
      "¿Quién tendría el escritorio más caótico con orgullo?",
      "¿Quién sería empleado del mes y aun así se quejaría?",
      "¿Quién llevaría snacks y compraría la lealtad de todos?",
      "¿Quién mandaría un 'según lo hablado' con veneno elegante?",
      "¿Quién haría como que trabaja cuando pasa alguien importante?",
      "¿Quién sería capaz de abrir una hoja Excel para planear una merienda?",
      "¿Quién acabaría liderando algo sin saber cómo entró ahí?",
      "¿Quién diría 'esto es rápido' y tardaría tres horas?",
      "¿Quién tendría más probabilidades de compartir pantalla con algo comprometedor abierto?",
      "¿Quién se pondría nervioso al ver 'tenemos que hablar' en Teams?",
      "¿Quién contestaría un email con un audio si pudiera?",
      "¿Quién haría política de oficina sin admitirlo?",
      "¿Quién sería el más peligroso con una impresora bloqueada?",
      "¿Quién pediría vacaciones con una estrategia digna de atraco?",
      "¿Quién se tomaría como misión personal arreglar algo que nadie pidió?",
      "¿Quién diría que está saturado y aceptaría otra tarea?",
      "¿Quién se escondería en el baño para sobrevivir socialmente?",
      "¿Quién sería el primero en abandonar el 'afterwork' por agotamiento social?",
      "¿Quién pondría una foto de su mascota como foto de perfil para caer bien?",
      "¿Quién usaría jerga laboral en su vida personal sin darse cuenta?",
      "¿Quién llevaría una taza 'oficialmente de vacaciones' días antes de irse?",
      "¿Quién fingiría una llamada importante para salir de una conversación aburrida?",
      "¿Quién se apuntaría a un curso obligatorio para no trabajar ese día?",
      "¿Quién sería el primero en notar que falta café en la oficina?",
      "¿Quién tendría un segundo monitor solo para ver series?",
      "¿Quién respondería un correo a las 2 am para parecer productivo?",
      "¿Quién propondría una reunión presencial para algo que se arreglaba en dos mensajes?"
    ]
  },
  {
    "id": "dinero_cutrerio",
    "name": "Dinero, compras y cutrerío",
    "emoji": "💸",
    "questions": [
      "¿Quién compraría algo inútil solo porque estaba al 70%?",
      "¿Quién tendría una suscripción que paga desde hace años sin saberlo?",
      "¿Quién invitaría y luego sufriría en silencio mirando la cuenta?",
      "¿Quién negociaría hasta en una máquina expendedora?",
      "¿Quién se haría rico con una idea absurda que nadie entiende?",
      "¿Quién prestaría dinero y le daría vergüenza pedirlo de vuelta?",
      "¿Quién compraría el regalo más caro para compensar no saber qué regalar?",
      "¿Quién perdería dinero por no leer la letra pequeña?",
      "¿Quién usaría cupones como si fueran armas de guerra?",
      "¿Quién pediría la cuenta y haría matemáticas imposibles?",
      "¿Quién ahorraría para algo serio y acabaría comprando una tontería luminosa?",
      "¿Quién tendría monedas sueltas en sitios anatómicamente inexplicables del bolso o mochila?",
      "¿Quién gastaría más en envío que en el producto?",
      "¿Quién compraría una freidora de aire y se sentiría adulto responsable?",
      "¿Quién caería en una compra impulsiva a medianoche?",
      "¿Quién diría 'me lo merezco' como justificación económica universal?",
      "¿Quién haría Bizum de 1,37€ sin temblarle el pulso?",
      "¿Quién sería capaz de dividir una cuenta como si fuera ingeniería aeroespacial?",
      "¿Quién se apuntaría a un curso para hacerse millonario en una semana?",
      "¿Quién tendría más tickets guardados que recuerdos felices?",
      "¿Quién compraría por internet algo y olvidaría que lo pidió?",
      "¿Quién se sentiría estafado por una bolsa de patatas medio vacía?",
      "¿Quién sería el peor tesorero de una peña?",
      "¿Quién gastaría una fortuna en algo que llama 'inversión'?",
      "¿Quién pediría comida a domicilio estando a 200 metros del bar?",
      "¿Quién tendría más probabilidades de revender una entrada con discurso ético raro?",
      "¿Quién regatearía por deporte?",
      "¿Quién tendría una hucha emocional que rompe cada viernes?",
      "¿Quién sería capaz de ahorrar en calefacción pero no en caprichos?",
      "¿Quién acabaría comprando un producto por culpa del anuncio más cutre?",
      "¿Quién devolvería un producto después de haberlo usado?",
      "¿Quién pediría que le regalen una cosa cara porque 'es que es muy especial'?",
      "¿Quién se llevaría los sobres de azúcar y las servilletas de un bar?",
      "¿Quién elegiría el gasolinera más barata aunque esté a 20 km?",
      "¿Quién regatearía en un mercadillo por algo que cuesta 2 euros?",
      "¿Quién sería capaz de pedir el menú del día y pedir cambios en todos los platos?",
      "¿Quién haría un bizum de 0,50 céntimos por una pegatina?",
      "¿Quién tendría más tarjetas de fidelidad que amigos?",
      "¿Quién compraría un producto en oferta aunque no lo necesite?",
      "¿Quién se sentiría millonario por encontrar 5 euros en un bolsillo?"
    ]
  },
  {
    "id": "casa_convivencia",
    "name": "Casa y convivencia",
    "emoji": "🏠",
    "questions": [
      "¿Quién dejaría una taza en una habitación y la declararía patrimonio familiar?",
      "¿Quién tendría una silla de ropa con estratos geológicos?",
      "¿Quién compraría plantas para verlas morir con estilo?",
      "¿Quién sería el vecino más cotilla con fachada de discreto?",
      "¿Quién montaría un mueble y le sobrarían piezas importantes?",
      "¿Quién tendría una nevera con misterios biológicos?",
      "¿Quién pondría una alarma para sacar la basura y la ignoraría con convicción?",
      "¿Quién sería el mejor anfitrión aunque luego necesite tres días de recuperación?",
      "¿Quién quemaría unas tostadas y diría que es punto ahumado?",
      "¿Quién no tiraría una caja porque 'puede servir'?",
      "¿Quién discutiría con un electrodoméstico y perdería?",
      "¿Quién tendría el cajón del caos más impresionante?",
      "¿Quién limpiaría a fondo justo antes de que venga alguien y luego enseñaría la casa?",
      "¿Quién sería incapaz de cambiar el rollo de papel sin hacer drama?",
      "¿Quién convertiría ordenar un armario en viaje emocional al pasado?",
      "¿Quién tendría más probabilidades de perder las llaves dentro de casa?",
      "¿Quién decoraría con criterio discutible y mucha seguridad?",
      "¿Quién se tomaría una barbacoa como competición olímpica?",
      "¿Quién abriría todas las ventanas aunque haga frío polar?",
      "¿Quién tendría más tuppers sin tapa que ilusiones?",
      "¿Quién sería el primero en quejarse del ruido y luego hacer más ruido?",
      "¿Quién pondría nombre al robot aspirador?",
      "¿Quién tendría una manta favorita con valor sentimental excesivo?",
      "¿Quién convertiría una mudanza en una tragedia griega?",
      "¿Quién dejaría cargadores enchufados como trampas modernas?",
      "¿Quién se compraría una herramienta para usarla una vez y venerarla siempre?",
      "¿Quién sería capaz de cenar de pie para no manchar platos?",
      "¿Quién diría 'luego lo recojo' y abriría un portal temporal?",
      "¿Quién tendría la casa impecable salvo un rincón prohibido?",
      "¿Quién escondería el desorden en un armario justo antes de abrir la puerta?",
      "¿Quién usaría la ducha como sala de conciertos?",
      "¿Quién pondría normas de convivencia después de la primera cena?",
      "¿Quién llenaría el congelador de comida que nunca llegará a comer?",
      "¿Quién sería capaz de poner una lavadora con una sola prenda?",
      "¿Quién se mudaría y dejaría su antigua habitación como si hubiera pasado una tormenta?",
      "¿Quién coleccionaría tuppers de plástico de la comida a domicilio?",
      "¿Quién tendría más pares de zapatillas viejas que dignidad?",
      "¿Quién pondría una planta artificial para no tener que regarla?",
      "¿Quién usaría el microondas para todo menos para calentar comida?",
      "¿Quién perdería las llaves de casa dentro de casa semanalmente?"
    ]
  },
  {
    "id": "pueblo_familia",
    "name": "Pueblo y familia",
    "emoji": "🌄",
    "questions": [
      "¿Quién conocería a todo el pueblo aunque diga que no conoce a nadie?",
      "¿Quién sería el primero en salir en una foto del periódico local?",
      "¿Quién defendería su pueblo como si fuera la capital del planeta?",
      "¿Quién se tomaría una competición de peñas como asunto de Estado?",
      "¿Quién acabaría bailando con una señora desconocida en la verbena?",
      "¿Quién preguntaría '¿y este de quién es?' en cada reunión?",
      "¿Quién se llevaría comida para tres días después de visitar a la familia?",
      "¿Quién tendría una anécdota con cada persona de la plaza?",
      "¿Quién haría ruta gastronómica sin salir de la misma calle?",
      "¿Quién sería pregonero perfecto y peligroso a la vez?",
      "¿Quién se emocionaría con una canción antigua en mitad de la sobremesa?",
      "¿Quién llegaría a comer y se quedaría hasta desayunar?",
      "¿Quién discutiría por la receta correcta de algo que nadie cocina igual?",
      "¿Quién sacaría una silla a la puerta como declaración de intenciones?",
      "¿Quién tendría más probabilidades de entrar en una rifa sin saber el premio?",
      "¿Quién haría de guía turístico exagerando monumentos pequeños?",
      "¿Quién convertiría una visita familiar en rueda de prensa?",
      "¿Quién se apuntaría a cualquier tradición si hay comida después?",
      "¿Quién tendría más peligro con una charanga cerca?",
      "¿Quién sería capaz de conocer un parentesco de memoria hasta cuarta generación?",
      "¿Quién llevaría postre aunque nadie lo pidió y todos lo necesitaban?",
      "¿Quién se indignaría si alguien critica la fiesta del pueblo?",
      "¿Quién acabaría sentado con los mayores escuchando secretos históricos?",
      "¿Quién sería el primero en decir 'esto antes era mejor'?",
      "¿Quién se pondría demasiado competitivo en un bingo familiar?",
      "¿Quién tendría un saludo distinto para cada vecino?",
      "¿Quién organizaría un campeonato improvisado de cualquier cosa?",
      "¿Quién saldría a comprar pan y volvería dos horas después con tres historias?",
      "¿Quién heredaría oficialmente el papel de cotilla noble de la familia?",
      "¿Quién sería capaz de montar una fiesta con una caja de cervezas y una silla rota?",
      "¿Quién sería el encargado de encender la barbacoa y quemaría las cejas?",
      "¿Quién se pondría a bailar sevillanas aunque no sepa?",
      "¿Quién llevaría a su perro a la fiesta del pueblo como si fuera un familiar más?",
      "¿Quién sería el primero en ofrecerse a hacer el vermú?",
      "¿Quién se empeñaría en que todos se pongan la camiseta del pueblo para la foto?",
      "¿Quién perdería a un niño en las fiestas?",
      "¿Quién se colaría en la barra del bar a ayudar 'porque sí'?",
      "¿Quién sería el primero en pedir la palabra en el turno de quejas del ayuntamiento?",
      "¿Quién se sabría todas las canciones de la orquesta?",
      "¿Quién se apuntaría a los juegos tradicionales y se lesionaría?"
    ]
  },
  {
    "id": "absurdo_total",
    "name": "Absurdo total",
    "emoji": "🌀",
    "questions": [
      "¿Quién sería elegido alcalde de una isla llena de patos?",
      "¿Quién discutiría con una estatua porque le mira raro?",
      "¿Quién abriría un museo dedicado a sus propios fracasos?",
      "¿Quién intentaría enseñar trucos a una piedra?",
      "¿Quién fundaría una religión alrededor de una croqueta?",
      "¿Quién perdería una carrera contra una tortuga y pediría revancha?",
      "¿Quién pondría nombre a todos los objetos de su casa?",
      "¿Quién sería arrestado por exceso de entusiasmo?",
      "¿Quién haría una rueda de prensa por un malentendido tonto?",
      "¿Quién podría hacerse famoso por caerse con estilo?",
      "¿Quién convertiría una partida de parchís en cuestión de honor?",
      "¿Quién tendría una pelea épica con una puerta automática?",
      "¿Quién sería protagonista de un anuncio rarísimo de yogures?",
      "¿Quién defendería una teoría absurda con gráficos inventados?",
      "¿Quién lloraría viendo un anuncio de detergente?",
      "¿Quién intentaría negociar con una cabra?",
      "¿Quién montaría una empresa de alquiler de sombras?",
      "¿Quién sería el villano más adorable de una película mala?",
      "¿Quién se perdería en una tienda pequeña y pediría coordenadas?",
      "¿Quién escribiría sus memorias después de una tarde intensa?",
      "¿Quién organizaría un funeral simbólico para una planta seca?",
      "¿Quién pondría normas oficiales para comer pipas?",
      "¿Quién se haría una camiseta con una frase que nadie entiende?",
      "¿Quién pediría perdón a un maniquí por chocarse con él?",
      "¿Quién inventaría un deporte peligroso con una escoba?",
      "¿Quién sería capaz de convertir un calcetín perdido en misterio nacional?",
      "¿Quién protagonizaría una batalla contra una sombrilla?",
      "¿Quién adoptaría un cono de tráfico como mascota emocional?",
      "¿Quién tendría un club de fans formado por señoras de una panadería?",
      "¿Quién diría 'esto es una señal' ante cualquier casualidad ridícula?"
    ]
  },
  {
    "id": "verguenza_ajena",
    "name": "Vergüenza ajena",
    "emoji": "🙈",
    "questions": [
      "¿Quién saludaría a alguien que no le estaba saludando?",
      "¿Quién se despediría dos veces y seguiría caminando en la misma dirección?",
      "¿Quién contaría un chiste y tendría que explicarlo con sufrimiento?",
      "¿Quién se tropezaría y fingiría que era parte del plan?",
      "¿Quién mandaría un audio y descubriría que se oye algo peor de fondo?",
      "¿Quién intentaría hablar en otro idioma y acabaría mezclando tres?",
      "¿Quién aplaudiría cuando nadie más aplaude?",
      "¿Quién se sentaría en el sitio equivocado y defendería su derecho a estar allí?",
      "¿Quién diría una frase épica y se le trabaría la lengua?",
      "¿Quién llamaría mamá a quien no debe?",
      "¿Quién pondría una canción para lucirse y saldría un anuncio horrible?",
      "¿Quién se equivocaría de persona al contar un secreto?",
      "¿Quién intentaría entrar por una puerta que se abre hacia el otro lado?",
      "¿Quién respondería 'igualmente' cuando no toca?",
      "¿Quién haría una reverencia mental después de decir una tontería?",
      "¿Quién tendría más probabilidades de caerse en cámara lenta?",
      "¿Quién se equivocaría de chat con una confianza dolorosa?",
      "¿Quién saldría en una foto importante justo parpadeando?",
      "¿Quién empezaría una frase y se arrepentiría a mitad?",
      "¿Quién intentaría ser misterioso y parecería perdido?",
      "¿Quién se pondría nervioso pagando y bloquearía la cola entera?",
      "¿Quién sería capaz de confundirse de coche y saludar dentro?",
      "¿Quién olvidaría el nombre de alguien justo después de oírlo?",
      "¿Quién intentaría decir algo profundo y sonaría a galleta de la suerte?",
      "¿Quién leería mal una palabra y cambiaría el sentido de toda la conversación?",
      "¿Quién haría un gesto cariñoso demasiado pronto?",
      "¿Quién fingiría saber de qué hablan hasta que le preguntan directamente?",
      "¿Quién lanzaría una mirada cómplice a la persona equivocada?",
      "¿Quién se reiría en el momento menos apropiado?",
      "¿Quién viviría una escena de vergüenza y la contaría esa misma noche?"
    ]
  },
  {
    "id": "personalidad_manias",
    "name": "Personalidad y manías",
    "emoji": "🧠",
    "questions": [
      "¿Quién se pondría competitivo con una tontería de sobremesa?",
      "¿Quién cambiaría de opinión tres veces y defendería las tres?",
      "¿Quién dramatizaría por algo pequeño con talento teatral?",
      "¿Quién intentaría parecer tranquilo estando completamente en llamas por dentro?",
      "¿Quién empezaría un hobby nuevo cada mes y compraría todo el material?",
      "¿Quién se obsesionaría con una canción hasta arruinarla para todos?",
      "¿Quién habla solo en voz alta y luego dice que estaba pensando?",
      "¿Quién sería el más testarudo en una discusión absurda?",
      "¿Quién se motivaría a medianoche para cambiar su vida entera?",
      "¿Quién abandonaría una dieta por una excusa poética?",
      "¿Quién pediría perdón aunque no tenga culpa ni relación con el problema?",
      "¿Quién sería el más fácil de asustar con una sombra?",
      "¿Quién tendría plan B, C y D para ir a comprar pan?",
      "¿Quién convertiría una pequeña victoria en celebración nacional?",
      "¿Quién necesita más validación con menos señales?",
      "¿Quién se pondría filosófico después de comer demasiado?",
      "¿Quién tendría una manía tan rara que parece inventada?",
      "¿Quién sería capaz de ordenar algo y no encontrarlo nunca más?",
      "¿Quién se inventaría reglas personales para todo?",
      "¿Quién sería el más intenso explicando una opinión sencilla?",
      "¿Quién guardaría rencor por una partida de hace años?",
      "¿Quién tendría más rituales antes de salir de casa?",
      "¿Quién respondería a una crítica con una novela emocional?",
      "¿Quién sería incapaz de estar cinco minutos sin hacer ruido?",
      "¿Quién se haría el duro y lloraría con una escena de dibujos?",
      "¿Quién tendría más probabilidades de decir 'no estoy enfadado' estando hirviendo?",
      "¿Quién analiza demasiado cada palabra de los demás?",
      "¿Quién sería capaz de llevar la contraria por deporte?",
      "¿Quién convertiría una compra simple en una decisión existencial?",
      "¿Quién tendría más cara de inocente siendo el culpable?"
    ]
  },
  {
    "id": "supervivencia_caos",
    "name": "Supervivencia y caos",
    "emoji": "🧟",
    "questions": [
      "¿Quién sería el primero en morir en un apocalipsis zombie por cotillear?",
      "¿Quién se haría líder del refugio sin que nadie le votara?",
      "¿Quién gastaría todas las provisiones el primer día por ansiedad?",
      "¿Quién intentaría domesticar a un animal salvaje con voz dulce?",
      "¿Quién vigilaría de noche y se quedaría dormido con orgullo?",
      "¿Quién inventaría una herramienta inútil y la llamaría prototipo?",
      "¿Quién encontraría comida por pura suerte y se creería explorador?",
      "¿Quién se asustaría de su propia sombra y culparía al viento?",
      "¿Quién haría un plan perfecto y luego no lo seguiría?",
      "¿Quién intentaría negociar con los zombies?",
      "¿Quién convertiría el búnker en comunidad de vecinos con normas?",
      "¿Quién se perdería buscando ayuda a veinte metros del grupo?",
      "¿Quién contaría chistes en el peor momento posible?",
      "¿Quién haría una bandera oficial para el campamento?",
      "¿Quién intentaría resolverlo todo viendo tutoriales descargados?",
      "¿Quién escondería provisiones secretas y luego olvidaría dónde?",
      "¿Quién sería más peligroso con una linterna que con cualquier arma?",
      "¿Quién diría 'yo sé hacer fuego' y produciría humo triste?",
      "¿Quién convertiría una emergencia en reunión organizativa?",
      "¿Quién tendría más probabilidades de llamar la atención de todos los enemigos?",
      "¿Quién se preocuparía más por cargar el móvil que por sobrevivir?",
      "¿Quién intentaría poner WiFi al refugio?",
      "¿Quién sería capaz de discutir el reparto de tareas hasta el amanecer?",
      "¿Quién se uniría al bando equivocado por simpatía?",
      "¿Quién sobreviviría porque nadie espera que sobreviva?",
      "¿Quién llevaría snacks ocultos al fin del mundo?",
      "¿Quién sería el primero en inventar una moneda del apocalipsis?",
      "¿Quién se haría famoso después del desastre con un podcast?",
      "¿Quién intentaría ponerse guapo para el rescate?",
      "¿Quién escribiría un diario dramático desde el día uno?"
    ]
  },
  {
    "id": "viajes_aventuras",
    "name": "Viajes y aventuras",
    "emoji": "✈️",
    "questions": [
      "¿Quién se perdería usando GPS y además culparía al satélite?",
      "¿Quién llevaría una maleta gigante para una noche?",
      "¿Quién hablaría otro idioma con acento inventado y mucha seguridad?",
      "¿Quién planificaría cada minuto del viaje en una hoja de cálculo?",
      "¿Quién perdería el billete justo antes de entrar?",
      "¿Quién se haría amigo de alguien local el primer día?",
      "¿Quién elegiría restaurante solo por fotos bonitas y acabaría mal?",
      "¿Quién compraría un recuerdo absurdo y lo defendería como arte?",
      "¿Quién dormiría todo el trayecto y despertaría como si nada?",
      "¿Quién se quemaría el primer día aunque hubiera sombra?",
      "¿Quién pediría indicaciones y entendería exactamente lo contrario?",
      "¿Quién convertiría una escapada barata en ruina financiera?",
      "¿Quién haría cola para algo sin saber qué es?",
      "¿Quién perdería al grupo en un mercado y volvería con comida?",
      "¿Quién haría 200 fotos de la misma fachada?",
      "¿Quién se enamoraría de una ciudad en diez minutos?",
      "¿Quién sería guía del viaje sin que nadie lo nombrara?",
      "¿Quién olvidaría el cargador en el hotel y lo viviría como tragedia?",
      "¿Quién pediría lo más raro del menú por hacerse el valiente?",
      "¿Quién diría que controla el mapa y llevaría a todos en círculos?",
      "¿Quién intentaría aprovechar tanto el viaje que agotaría al grupo?",
      "¿Quién se quedaría mirando souvenirs como si eligiera herencia familiar?",
      "¿Quién sería capaz de perder el pasaporte dentro de la mochila?",
      "¿Quién volvería del viaje hablando como si hubiera vivido allí años?",
      "¿Quién pediría una foto y posaría durante demasiado tiempo?",
      "¿Quién acabaría en una fiesta local sin saber cómo?",
      "¿Quién tendría más probabilidades de enamorarse de un guía turístico?",
      "¿Quién haría una reseña mental de cada baño del viaje?",
      "¿Quién sería el primero en decir 'aquí se vive mejor'?",
      "¿Quién convertiría un retraso de tren en aventura épica?"
    ]
  },
  {
    "id": "comida_gula",
    "name": "Comida y gula",
    "emoji": "🍔",
    "questions": [
      "¿Quién pediría postre diciendo que no tiene hambre?",
      "¿Quién robaría patatas del plato ajeno con cara inocente?",
      "¿Quién defendería una combinación de comida absolutamente ilegal?",
      "¿Quién juzgaría un restaurante por el pan?",
      "¿Quién sería capaz de comer picante y fingir que no sufre?",
      "¿Quién pediría para compartir y luego protegería su parte?",
      "¿Quién haría fotos a la comida antes de preguntar si está bueno?",
      "¿Quién convertiría una cena en análisis gastronómico de televisión?",
      "¿Quién se mancharía con la primera mordida?",
      "¿Quién elegiría siempre el plato que tarda más?",
      "¿Quién repetiría aunque esté al borde del colapso?",
      "¿Quién sería capaz de desayunar sobras frías con orgullo?",
      "¿Quién escondería snacks como si viviera en guerra?",
      "¿Quién tendría opiniones demasiado fuertes sobre la tortilla?",
      "¿Quién sería el primero en oler comida desde otra habitación?",
      "¿Quién pediría algo sano y acabaría probando todo lo demás?",
      "¿Quién se ofendería si no le dejan probar un bocado?",
      "¿Quién haría de crítico culinario sin saber cocinar?",
      "¿Quién compraría ingredientes raros para usarlos una vez?",
      "¿Quién haría una barbacoa como si fuese un ritual ancestral?",
      "¿Quién se pondría emocional con un buen bocadillo?",
      "¿Quién diría 'solo voy a picar algo' y cenaría dos veces?",
      "¿Quién se llevaría comida de una fiesta sin disimulo?",
      "¿Quién quemaría algo y le llamaría cocina experimental?",
      "¿Quién sería capaz de discutir por la última croqueta?",
      "¿Quién pediría comida a domicilio después de haber comprado comida?",
      "¿Quién sabría dónde está el mejor bar de cada calle?",
      "¿Quién comería algo caducado tras olerlo con confianza?",
      "¿Quién convertiría una dieta en una narrativa de superación?",
      "¿Quién prepararía demasiada comida y lo llamaría previsión?"
    ]
  },
  {
    "id": "familia_navidad",
    "name": "Familia, Navidad y compromisos",
    "emoji": "🎄",
    "questions": [
      "¿Quién sería el primero en sacar un tema incómodo en la cena familiar?",
      "¿Quién compraría regalos a última hora y acertaría por milagro?",
      "¿Quién fingiría que le gusta un regalo horrible?",
      "¿Quién se sentaría estratégicamente lejos de la conversación peligrosa?",
      "¿Quién acabaría explicando tecnología a cinco familiares?",
      "¿Quién se pondría nervioso cuando le preguntan por su vida?",
      "¿Quién llevaría postre comprado y diría que 'es de confianza'?",
      "¿Quién sería el encargado oficial de abrir botellas?",
      "¿Quién ganaría una discusión familiar usando datos de dudosa procedencia?",
      "¿Quién se escaparía a la cocina para evitar preguntas?",
      "¿Quién acabaría cantando villancicos con demasiada entrega?",
      "¿Quién haría balance del año como si diera resultados empresariales?",
      "¿Quién tendría más papeletas de dormirse en el sofá?",
      "¿Quién se tomaría el amigo invisible como examen final?",
      "¿Quién sería capaz de empaquetar un regalo con cinta suficiente para tres mudanzas?",
      "¿Quién tendría una respuesta preparada para cada pregunta incómoda?",
      "¿Quién se llevaría sobras suficientes para sobrevivir enero?",
      "¿Quién se pondría nostálgico viendo fotos antiguas?",
      "¿Quién sería el primero en decir 'el año que viene menos comida'?",
      "¿Quién discutiría por el mando de la tele?",
      "¿Quién haría de árbitro entre dos generaciones?",
      "¿Quién exageraría una anécdota de la infancia delante de todos?",
      "¿Quién acabaría haciendo un discurso inesperado?",
      "¿Quién se pondría competitivo con los juegos de mesa familiares?",
      "¿Quién fingiría entender una historia larguísima de un tío segundo?",
      "¿Quién sería el primero en marcharse y el último en conseguirlo?",
      "¿Quién tendría más probabilidades de repetir ropa elegante de otra boda?",
      "¿Quién sería capaz de llorar con un anuncio navideño?",
      "¿Quién llevaría conversación de emergencia preparada?",
      "¿Quién pediría café para aguantar y acabaría hiperactivo?"
    ]
  },
  {
    "id": "bodas_eventos",
    "name": "Bodas, bautizos y saraos",
    "emoji": "💃",
    "questions": [
      "¿Quién se tomaría una boda como si fuera Eurovisión?",
      "¿Quién sería el primero en llorar sin conocer bien a los novios?",
      "¿Quién acabaría liderando la conga con autoridad moral?",
      "¿Quién se quitaría los zapatos demasiado pronto?",
      "¿Quién intentaría ligar con alguien de una mesa lejana?",
      "¿Quién se haría amigo del fotógrafo?",
      "¿Quién tendría más peligro con barra libre y una canción de infancia?",
      "¿Quién se llevaría centros de mesa como trofeo?",
      "¿Quién daría un discurso que nadie pidió?",
      "¿Quién se colaría en fotos de otras familias?",
      "¿Quién sería el primero en preguntar cuándo sale la comida?",
      "¿Quién bailaría con una tía abuela como si fuera final de concurso?",
      "¿Quién se emocionaría con el vídeo de fotos aunque esté mal editado?",
      "¿Quién se perdería buscando el baño y aparecería en otra celebración?",
      "¿Quién haría crítica gastronómica del menú entero?",
      "¿Quién acabaría sujetando el bolso de todo el mundo?",
      "¿Quién iría demasiado arreglado para una cosa informal?",
      "¿Quién iría demasiado informal para una cosa arreglada?",
      "¿Quién tendría más probabilidades de pillar el ramo por accidente?",
      "¿Quién se sabría todos los pasos de una canción de verbena?",
      "¿Quién confundiría parientes y saludaría con demasiada confianza?",
      "¿Quién sería capaz de pedir otra canción cuando ya están recogiendo?",
      "¿Quién necesitaría una misión para sobrevivir a la mesa asignada?",
      "¿Quién tendría más papeletas de salir en el vídeo haciendo algo raro?",
      "¿Quién haría grupo temporal con desconocidos que jamás volverá a ver?",
      "¿Quién se pondría profundo con el camarero?",
      "¿Quién sería el primero en decir 'esta boda sí que está bien organizada'?",
      "¿Quién intentaría llevarse comida discretamente y fallaría?",
      "¿Quién acabaría en la mesa de niños por energía mental?",
      "¿Quién cerraría la pista aunque ya no quede música?"
    ]
  },
  {
    "id": "moral_dudosa",
    "name": "Decisiones de moral dudosa",
    "emoji": "⚖️",
    "questions": [
      "¿Quién se quedaría con el cambio extra y luego tendría conflicto interno?",
      "¿Quién se comería el último trozo sin preguntar y diría que pensaba que nadie quería?",
      "¿Quién mentiría para evitar un plan y luego subiría una historia fuera?",
      "¿Quién copiaría una excusa ajena y la contaría mejor?",
      "¿Quién colaría a alguien en una fila con una explicación emocional?",
      "¿Quién se llevaría un champú de hotel y lo llamaría derecho adquirido?",
      "¿Quién fingiría no haber visto un mensaje para ganar tiempo?",
      "¿Quién guardaría información estratégica hasta que le convenga?",
      "¿Quién rompería algo pequeño y miraría al techo?",
      "¿Quién culparía al algoritmo de una mala decisión propia?",
      "¿Quién diría una verdad incómoda con una sonrisa peligrosa?",
      "¿Quién usaría 'es broma' como airbag social?",
      "¿Quién sería capaz de aparcar mal y justificarlo filosóficamente?",
      "¿Quién aceptaría un favor y luego desaparecería elegantemente?",
      "¿Quién se saltaría una norma absurda y convencería a todos de que es justicia?",
      "¿Quién sería el primero en hacer trampa en un juego familiar?",
      "¿Quién escondería una prueba para no alargar una discusión?",
      "¿Quién se quedaría el mejor sitio diciendo que 'ya estaba aquí'?",
      "¿Quién diría que no tiene hambre y luego atacaría tu plato?",
      "¿Quién usaría la culpa como herramienta de negociación?",
      "¿Quién sería capaz de cambiar de equipo si va perdiendo?",
      "¿Quién se apropiaría de una idea ajena diciendo 'justo iba a decir eso'?",
      "¿Quién haría una promesa sabiendo que depende de su yo del futuro?",
      "¿Quién se pondría digno después de haber empezado el lío?",
      "¿Quién mandaría una indirecta y negaría que era indirecta?",
      "¿Quién se saltaría el orden de llegada con cara de inocente?",
      "¿Quién usaría el cumpleaños como carta comodín durante una semana?",
      "¿Quién sería peligrosamente bueno convenciendo al grupo de una mala idea?",
      "¿Quién mentiría sobre haber visto una serie para entrar en la conversación?",
      "¿Quién diría 'yo no he sido' demasiado rápido?"
    ]
  },
  {
    "id": "lujo_miseria",
    "name": "Lujo, postureo y miseria",
    "emoji": "🥂",
    "questions": [
      "¿Quién pediría lo más barato del menú pronunciándolo como si fuera gourmet?",
      "¿Quién aparentaría control económico con la cuenta temblando?",
      "¿Quién se haría fotos en un hotel que no puede pagar?",
      "¿Quién diría 'esto es una experiencia' para justificar un sablazo?",
      "¿Quién se sentiría famoso por llevar gafas de sol en interior?",
      "¿Quién compraría algo de marca y viviría de arroz una semana?",
      "¿Quién tendría gustos de millonario y presupuesto de estudiante?",
      "¿Quién pediría agua del grifo con elegancia imperial?",
      "¿Quién se colaría mentalmente en un ambiente fino y lo arruinaría con una frase?",
      "¿Quién sería capaz de hacer una review seria de unas aceitunas gratis?",
      "¿Quién se pondría ropa nueva y lo anunciaría sin decirlo?",
      "¿Quién fingiría entender una carta de vinos?",
      "¿Quién defendería que un sitio caro 'merece la pena' aunque salga con hambre?",
      "¿Quién haría un plan barato y lo vendería como alternativo?",
      "¿Quién tendría más probabilidades de llamar inversión a un capricho?",
      "¿Quién posturearía con un café y portátil sin trabajar nada?",
      "¿Quién se emocionaría en un buffet libre como si fuera una herencia?",
      "¿Quién se compraría algo dorado y diría que es discreto?",
      "¿Quién transformaría un picnic cutre en evento bohemio?",
      "¿Quién sería capaz de pedir una foto repitiendo la pose diez veces?",
      "¿Quién se sentiría superior por descubrir un sitio escondido?",
      "¿Quién convertiría una oferta del supermercado en triunfo personal?",
      "¿Quién pondría voz elegante al decir una tontería?",
      "¿Quién sería más feliz en una terraza cara que en su propia casa?",
      "¿Quién tendría más peligro con una copa en la mano y una vista bonita?",
      "¿Quién presumiría de algo prestado?",
      "¿Quién se apuntaría a una cata solo por los aperitivos?",
      "¿Quién intentaría parecer misterioso y acabaría pareciendo cansado?",
      "¿Quién llevaría un look calculado para decir que 'se puso lo primero'?",
      "¿Quién viviría por encima de sus posibilidades durante exactamente una noche?"
    ]
  },
  {
    "id": "ofensa_sensibilidad",
    "name": "Ofendiditos y sensibles",
    "emoji": "🥲",
    "questions": [
      "¿Quién se ofendería por una broma que no iba con él?",
      "¿Quién fingiría que no le afecta y escribiría un ensayo mental?",
      "¿Quién sería capaz de recordar una frase exacta de hace cuatro años?",
      "¿Quién diría 'me da igual' con la voz más dolida del mundo?",
      "¿Quién necesitaría tres días para procesar un comentario tonto?",
      "¿Quién perdonaría pero sacaría el tema en 2031?",
      "¿Quién se emocionaría con un gesto pequeño y lo convertiría en evento?",
      "¿Quién pondría cara normal mientras por dentro redacta un comunicado?",
      "¿Quién pediría explicaciones por un cambio de tono en un mensaje?",
      "¿Quién diría que no pasa nada cuando pasa absolutamente todo?",
      "¿Quién se sentiría atacado por un horóscopo genérico?",
      "¿Quién sería capaz de llorar de rabia por perder un juego?",
      "¿Quién interpretaría un silencio como juicio final?",
      "¿Quién se pondría sentimental por una foto antigua borrosa?",
      "¿Quién se tomaría como personal una crítica al pan tostado?",
      "¿Quién necesitaría una disculpa con estructura y conclusión?",
      "¿Quién se indignaría con una injusticia mínima pero real?",
      "¿Quién se haría el fuerte y luego pediría un abrazo?",
      "¿Quién convertiría un malentendido en terapia de grupo?",
      "¿Quién notaría un cambio de emoji como señal de guerra?",
      "¿Quién sería el primero en decir 'no estoy enfadado' estando nuclear?",
      "¿Quién haría drama porque nadie le preguntó qué quería pedir?",
      "¿Quién se sentiría excluido de un plan al que no quería ir?",
      "¿Quién llevaría una lista mental de agravios pequeños?",
      "¿Quién sería más fácil de herir y más difícil de admitirlo?",
      "¿Quién interpretaría una mirada como editorial completa?",
      "¿Quién necesitaría un cierre emocional para una discusión sobre pizza?",
      "¿Quién se enfadaría consigo mismo por haberse enfadado?",
      "¿Quién haría de víctima y fiscal en la misma conversación?",
      "¿Quién acabaría pidiendo perdón por haber pedido perdón?"
    ]
  },
  {
    "id": "nostalgia_infancia",
    "name": "Nostalgia e infancia",
    "emoji": "🧸",
    "questions": [
      "¿Quién guardaría juguetes viejos como reliquias sagradas?",
      "¿Quién se emocionaría al oír una canción de dibujos animados?",
      "¿Quién tendría más historias vergonzosas del colegio?",
      "¿Quién sería el niño que hablaba demasiado en clase?",
      "¿Quién habría sido delegado con exceso de poder?",
      "¿Quién se habría comido el bocadillo antes del recreo?",
      "¿Quién mentiría diciendo que hizo los deberes y luego improvisaría?",
      "¿Quién tendría más probabilidades de haber tenido un diario dramático?",
      "¿Quién era capaz de hacer amigos en una cola del supermercado?",
      "¿Quién habría montado un club secreto con normas absurdas?",
      "¿Quién se tomaría demasiado en serio un partido en el patio?",
      "¿Quién habría llorado por perder una goma de borrar especial?",
      "¿Quién tendría una colección incomprensible de objetos pequeños?",
      "¿Quién habría sido pillado pasando una nota?",
      "¿Quién se habría inventado una enfermedad para no ir a clase?",
      "¿Quién tendría más posibilidades de haber sido protagonista de una excursión caótica?",
      "¿Quién habría escrito su nombre en todo para no perderlo y lo perdería igual?",
      "¿Quién seguiría usando frases de su infancia sin darse cuenta?",
      "¿Quién habría querido ser famoso por una razón absurda?",
      "¿Quién se acordaría de todos los juegos del recreo?",
      "¿Quién sería el que más ha cambiado desde pequeño?",
      "¿Quién tendría una foto infantil que explica demasiado?",
      "¿Quién habría llorado con una película que decía que no le importaba?",
      "¿Quién habría montado una tienda falsa con piedras y hojas?",
      "¿Quién se habría creído una mentira infantil durante demasiado tiempo?",
      "¿Quién sería capaz de volver a jugar como niño sin vergüenza?",
      "¿Quién tenía más papeletas de perderse en una excursión?",
      "¿Quién habría tenido un crush escolar absolutamente secreto y evidente?",
      "¿Quién habría sido el primero en hacerse una herida enseñando una tontería?",
      "¿Quién guarda todavía una versión idealizada de aquellos años?"
    ]
  },
  {
    "id": "salud_gimnasio",
    "name": "Gimnasio y vida sana fake",
    "emoji": "🏋️",
    "questions": [
      "¿Quién empezaría el lunes una vida sana que acaba el martes?",
      "¿Quién compraría ropa deportiva antes de hacer deporte?",
      "¿Quién subiría una foto del gimnasio y se iría a los diez minutos?",
      "¿Quién pediría ensalada y luego atacaría las patatas de todos?",
      "¿Quién tendría una botella enorme de agua como declaración de intenciones?",
      "¿Quién se lesionaría calentando?",
      "¿Quién convertiría caminar al bar en cardio?",
      "¿Quién hablaría de proteínas sin saber cuánto es una proteína?",
      "¿Quién se pondría una meta imposible con entusiasmo peligroso?",
      "¿Quién haría una dieta basada en excepciones?",
      "¿Quién compraría suplementos y olvidaría dormir?",
      "¿Quién se pesaría tres veces en un día buscando justicia?",
      "¿Quién diría 'hoy descanso' cinco días seguidos?",
      "¿Quién sería capaz de apuntarse a una carrera por una camiseta?",
      "¿Quién tendría más excusas creativas para no entrenar?",
      "¿Quién se tomaría un zumo verde como penitencia pública?",
      "¿Quién compararía agujetas como medallas de guerra?",
      "¿Quién haría estiramientos dramáticos delante de todos?",
      "¿Quién compraría una báscula inteligente para discutir con ella?",
      "¿Quién intentaría meditar y acabaría pensando en comida?",
      "¿Quién sería el primero en abandonar una caminata y pedir taxi?",
      "¿Quién tendría una app de salud ignorada con notificaciones tristes?",
      "¿Quién llamaría cheat meal a toda una semana?",
      "¿Quién convertiría una ruta sencilla en expedición alpina?",
      "¿Quién se sentiría atleta por subir escaleras una vez?",
      "¿Quién tendría más peligro con una pulsera de actividad y competitividad?",
      "¿Quién se apuntaría a yoga y acabaría haciendo comentarios fuera de lugar?",
      "¿Quién sería capaz de entrenar solo si hay recompensa comestible?",
      "¿Quién se compraría una esterilla para que decore el salón?",
      "¿Quién se motivaría más comprando material que usándolo?"
    ]
  },
  {
    "id": "conspiraciones",
    "name": "Conspiraciones y teorías locas",
    "emoji": "🛸",
    "questions": [
      "¿Quién creería una teoría absurda si viene con un vídeo largo?",
      "¿Quién vería señales ocultas en el ticket del supermercado?",
      "¿Quién acusaría al Mercurio retrógrado de sus malas decisiones?",
      "¿Quién tendría un tablero mental con hilos rojos imaginarios?",
      "¿Quién defendería que algo 'no puede ser casualidad' cada semana?",
      "¿Quién sería capaz de iniciar una secta alrededor de una app de notas?",
      "¿Quién sospecharía de una paloma demasiado quieta?",
      "¿Quién convertiría un sueño raro en predicción oficial?",
      "¿Quién tendría más probabilidades de comprar un curso de energías raras?",
      "¿Quién se tomaría un horóscopo como informe médico?",
      "¿Quién explicaría una coincidencia con una teoría de siete capas?",
      "¿Quién haría preguntas incómodas a una atracción de feria?",
      "¿Quién pensaría que el grupo tiene un infiltrado aunque no juegue a infiltrado?",
      "¿Quién sería capaz de desconfiar de una tostadora inteligente?",
      "¿Quién pondría nombre a una conspiración del vecindario?",
      "¿Quién tendría miedo de aceptar cookies pero contaría su vida online?",
      "¿Quién vería un documental raro y cambiaría de personalidad dos días?",
      "¿Quién sería capaz de hacer un podcast de misterio con una anécdota familiar?",
      "¿Quién diría 'abre los ojos' antes de una tontería monumental?",
      "¿Quién relacionaría una luz parpadeante con extraterrestres?",
      "¿Quién sospecharía del algoritmo por conocerlo demasiado bien?",
      "¿Quién creería que una canción sonó justo por destino?",
      "¿Quién tendría más probabilidades de hablar con plantas por recomendación energética?",
      "¿Quién inventaría una teoría sobre por qué siempre desaparecen los calcetines?",
      "¿Quién sería capaz de desconfiar de un mapa porque 'te quieren llevar por ahí'?",
      "¿Quién leería comentarios de internet y saldría con nueva personalidad?",
      "¿Quién tendría una explicación espiritual para llegar tarde?",
      "¿Quién montaría una investigación por una llamada perdida?",
      "¿Quién pensaría que un gato sabe demasiado?",
      "¿Quién convencería a alguien de una teoría absurda solo por entusiasmo?"
    ]
  },
  {
    "id": "crimen_misterio",
    "name": "Crimen ficticio y misterio",
    "emoji": "🕵️",
    "questions": [
      "¿Quién sería sospechoso en una serie solo por su forma de mirar?",
      "¿Quién resolvería un misterio pero no encontraría sus llaves?",
      "¿Quién sería el detective que acusa a todos en el primer capítulo?",
      "¿Quién tendría una coartada tan mala que parece mentira aunque sea verdad?",
      "¿Quién ocultaría pruebas por ordenar demasiado?",
      "¿Quién sería interrogado y hablaría de más por nervios?",
      "¿Quién descubriría al culpable por un detalle de decoración?",
      "¿Quién sería el vecino que siempre sabe algo?",
      "¿Quién haría una teoría brillante basada en una tontería?",
      "¿Quién sería el primero en tocar la prueba que nadie debía tocar?",
      "¿Quién tendría cara de culpable incluso ganando un sorteo?",
      "¿Quién se uniría a una investigación solo por el drama?",
      "¿Quién sería capaz de esconderse en el peor sitio posible?",
      "¿Quién acusaría al más inocente con total seguridad?",
      "¿Quién sería el personaje que parece inútil y salva el día?",
      "¿Quién se aprendería lenguaje policial viendo series?",
      "¿Quién tendría más probabilidades de dejar una pista ridícula?",
      "¿Quién haría un mapa del caso en una servilleta?",
      "¿Quién se tomaría un juego de misterio como examen de oposición?",
      "¿Quién pediría silencio dramático antes de revelar algo obvio?",
      "¿Quién sería el testigo que cambia la versión tres veces?",
      "¿Quién tendría más posibilidades de ser acusado por llevar guantes en verano?",
      "¿Quién resolvería el crimen por hambre, siguiendo olor a comida?",
      "¿Quién gritaría demasiado en una casa encantada?",
      "¿Quién sería capaz de entrevistar a un sospechoso con preguntas personales?",
      "¿Quién se escondería detrás de alguien más pequeño?",
      "¿Quién convertiría un escape room en tensión familiar?",
      "¿Quién tendría una lupa decorativa y se sentiría profesional?",
      "¿Quién sería el culpable perfecto porque nadie lo toma en serio?",
      "¿Quién narraría los hechos con voz de documental?"
    ]
  },
  {
    "id": "fama_tele",
    "name": "Famosos, tele y reality",
    "emoji": "📺",
    "questions": [
      "¿Quién entraría en un reality diciendo que va a ser discreto y sería protagonista?",
      "¿Quién lloraría en el confesionario por una discusión sobre comida?",
      "¿Quién se haría famoso por una frase accidental?",
      "¿Quién sería jurado cruel en un talent show?",
      "¿Quién daría una entrevista y se metería solo en otro lío?",
      "¿Quién tendría fandom y haters en la misma semana?",
      "¿Quién bailaría fatal pero con tanta fe que ganaría público?",
      "¿Quién sería expulsado de un concurso por exceso de sinceridad?",
      "¿Quién vendería su exclusiva por un bocadillo bien hecho?",
      "¿Quién tendría más probabilidades de decir 'yo soy muy natural' estando impostadísimo?",
      "¿Quién montaría drama por una nominación simbólica?",
      "¿Quién se creería celebrity tras 200 likes?",
      "¿Quién sería el representante de otro sin permiso?",
      "¿Quién haría de presentador aunque nadie se lo pidiera?",
      "¿Quién tendría un documental innecesario pero entretenido?",
      "¿Quién se inventaría una rivalidad para dar audiencia?",
      "¿Quién sería capaz de ganar un concurso sin entender las reglas?",
      "¿Quién tendría más peligro con un micrófono abierto?",
      "¿Quién lloraría viendo su vídeo de presentación?",
      "¿Quién se haría un discurso de ganador aunque quede último?",
      "¿Quién sería meme nacional por mirar raro?",
      "¿Quién tendría más posibilidades de confundir fama con responsabilidad?",
      "¿Quién sería capaz de pedir camerino en una fiesta de barrio?",
      "¿Quién sería el concursante que todos subestiman y luego arrasa?",
      "¿Quién se pondría gafas de sol para bajar al portal?",
      "¿Quién tendría una biografía titulada demasiado pronto?",
      "¿Quién se metería en una polémica por responder un comentario?",
      "¿Quién se emocionaría al oír aplausos aunque no sean para él?",
      "¿Quién sería el invitado que no se quiere ir del plató?",
      "¿Quién tendría frase de merchandising sin buscarlo?"
    ]
  },
  {
    "id": "universo_paralelo",
    "name": "Universos paralelos",
    "emoji": "🪐",
    "questions": [
      "¿Quién en otra vida sería rey absoluto de una república de gatos?",
      "¿Quién sería villano de película pero con agenda muy ordenada?",
      "¿Quién abriría una panadería en Marte y fracasaría por marketing?",
      "¿Quién sería maestro ninja de excusas?",
      "¿Quién en una fantasía medieval moriría por tocar algo prohibido?",
      "¿Quién sería el dragón que solo quiere dormir?",
      "¿Quién sobreviviría en una nave espacial por saber hacer tortilla?",
      "¿Quién sería un fantasma que cotillea en vez de asustar?",
      "¿Quién fundaría una ciudad donde la siesta es ley?",
      "¿Quién sería elegido oráculo y diría vaguedades útiles?",
      "¿Quién en un videojuego sería NPC con misiones raras?",
      "¿Quién sería superhéroe con poder absurdo pero práctico?",
      "¿Quién tendría como superpoder cancelar planes sin culpa?",
      "¿Quién sería pirata solo por la ropa?",
      "¿Quién montaría una taberna intergaláctica con tapas?",
      "¿Quién sería hechicero pero perdería la varita cada día?",
      "¿Quién sería emperador por accidente administrativo?",
      "¿Quién viviría en una película musical y cantaría sus problemas?",
      "¿Quién sería el monstruo adorable que todos adoptan?",
      "¿Quién abriría una consultoría emocional para robots?",
      "¿Quién sería detective de sueños absurdos?",
      "¿Quién tendría más probabilidades de romper la línea temporal por curiosidad?",
      "¿Quién sería guardián de un tesoro y lo gastaría?",
      "¿Quién en un apocalipsis mágico vendería merchandising?",
      "¿Quién sería estrella de un circo lunar sin saber hacer nada?",
      "¿Quién lideraría una rebelión por falta de snacks?",
      "¿Quién sería el elegido y pediría cambiar de turno?",
      "¿Quién se enamoraría de un holograma con buenas respuestas?",
      "¿Quién sería alcalde de una ciudad invisible?",
      "¿Quién tendría una profecía escrita con faltas de ortografía?"
    ]
  },
  {
    "id": "deporte_competicion",
    "name": "Deporte y competitividad",
    "emoji": "🏆",
    "questions": [
      "¿Quién celebraría ganar un juego tonto como si fuera Champions?",
      "¿Quién haría trampas en un campeonato de piedra, papel o tijera?",
      "¿Quién se lesionaría celebrando?",
      "¿Quién sería entrenador insoportable desde el banquillo?",
      "¿Quién perdería y culparía al terreno de juego?",
      "¿Quién se tomaría un partido amistoso como deuda familiar?",
      "¿Quién tendría más probabilidades de cantar victoria antes de tiempo?",
      "¿Quién sería capaz de discutir un punto durante veinte minutos?",
      "¿Quién elegiría equipo como si hiciera draft profesional?",
      "¿Quién ganaría por pura suerte y hablaría de estrategia?",
      "¿Quién se pondría una cinta en la cabeza para entrar en personaje?",
      "¿Quién sería el árbitro más corruptible por comida?",
      "¿Quién jugaría fatal pero animaría como nadie?",
      "¿Quién se frustraría con un juego de mesa infantil?",
      "¿Quién tendría más espíritu olímpico para subir escaleras?",
      "¿Quién perdería la dignidad por ganar una ronda?",
      "¿Quién entrenaría en secreto para una tontería?",
      "¿Quién sería capaz de inventar una lesión táctica?",
      "¿Quién tendría celebraciones preparadas para todo?",
      "¿Quién convertiría una derrota en relato heroico?",
      "¿Quién sería el primero en pedir revancha?",
      "¿Quién se tomaría las reglas como sugerencias?",
      "¿Quién haría un análisis postpartido sin que nadie lo pida?",
      "¿Quién tendría más probabilidades de motivar al equipo con frases de película?",
      "¿Quién se enfadaría con su propio rendimiento en un juego ridículo?",
      "¿Quién sería capaz de fichar a alguien por amistad y arrepentirse?",
      "¿Quién ganaría solo porque todos se confían?",
      "¿Quién sería el deportista retirado de un deporte que nunca practicó?",
      "¿Quién celebraría un empate como victoria moral?",
      "¿Quién haría calentamiento para jugar a las cartas?"
    ]
  },
  {
    "id": "mentiras_excusas",
    "name": "Mentiras y excusas",
    "emoji": "🤥",
    "questions": [
      "¿Quién inventaría una excusa tan larga que acabaría creyéndosela?",
      "¿Quién diría 'estoy llegando' desde la ducha?",
      "¿Quién fingiría no haber visto un mensaje con el móvil en la mano?",
      "¿Quién tendría más probabilidades de decir 'se me pasó' como estilo de vida?",
      "¿Quién mentiría fatal pero con mucho compromiso?",
      "¿Quién usaría una avería imaginaria para cancelar un plan?",
      "¿Quién improvisaría una coartada y metería demasiados detalles?",
      "¿Quién diría que no puede ir y aparecería en redes en otro sitio?",
      "¿Quién convertiría llegar tarde en accidente meteorológico?",
      "¿Quién culparía al tráfico aunque haya ido andando?",
      "¿Quién fingiría entender una película para no quedar mal?",
      "¿Quién diría que conoce un sitio y luego preguntaría la dirección?",
      "¿Quién prometería 'te aviso luego' y desaparecería en paz?",
      "¿Quién tendría una excusa diferente para cada día de la semana?",
      "¿Quién exageraría una pequeña molestia hasta parecer parte médico?",
      "¿Quién mentiría para no herir y acabaría liándola más?",
      "¿Quién diría 'lo tengo controlado' cuando claramente no?",
      "¿Quién se inventaría un compromiso familiar recurrente?",
      "¿Quién sería capaz de cancelar por cansancio social y llamarlo logística?",
      "¿Quién usaría una foto antigua como prueba actual?",
      "¿Quién fingiría dormir para no responder?",
      "¿Quién diría que no tiene batería con el móvil al 74%?",
      "¿Quién escondería una compra diciendo que 'lo tenía de antes'?",
      "¿Quién mentiría sobre la hora para que los demás lleguen puntuales?",
      "¿Quién intentaría cubrir una mentira con otra más absurda?",
      "¿Quién diría que no le importa y luego investigaría todo?",
      "¿Quién sería capaz de negar algo con pruebas delante?",
      "¿Quién inventaría una alergia social temporal?",
      "¿Quién pediría perdón antes de explicar qué ha hecho?",
      "¿Quién se libraría de todo porque da pena reñirle?"
    ]
  },
  {
    "id": "citas_amor",
    "name": "Citas y amor caótico",
    "emoji": "💘",
    "questions": [
      "¿Quién prepararía una primera cita con intensidad de aniversario?",
      "¿Quién volvería con alguien solo por nostalgia y una canción?",
      "¿Quién stalkearía perfiles antiguos y daría like sin querer?",
      "¿Quién tendría más probabilidades de enamorarse en vacaciones?",
      "¿Quién confundiría una respuesta amable con destino universal?",
      "¿Quién escribiría y borraría el mismo mensaje veinte veces?",
      "¿Quién pediría consejo al grupo y haría lo contrario?",
      "¿Quién sería cupido de todos menos de sí mismo?",
      "¿Quién haría una playlist para superar algo que duró dos semanas?",
      "¿Quién recordaría una conversación exacta de hace años?",
      "¿Quién tendría una cita perfecta y aun así encontraría un problema?",
      "¿Quién sería capaz de escribir una carta de amor en plena era digital?",
      "¿Quién se fijaría en la persona más incompatible disponible?",
      "¿Quién intentaría ligar contando una anécdota demasiado larga?",
      "¿Quién se pondría nervioso por un silencio de cinco minutos?",
      "¿Quién se enamoraría por cómo alguien escribe los mensajes?",
      "¿Quién tendría más probabilidades de decir 'yo no soy celoso' y luego investigarlo todo?",
      "¿Quién sería el más vulnerable a una mirada intensa?",
      "¿Quién usaría una excusa cultural para quedar con alguien?",
      "¿Quién sería capaz de tener un casi algo eternamente?",
      "¿Quién se montaría una película por un emoji nuevo?",
      "¿Quién se enamoraría de la idea de alguien antes que de alguien?",
      "¿Quién tendría más peligro con una conversación a las dos de la mañana?",
      "¿Quién volvería a abrir una puerta cerrada por puro aburrimiento?",
      "¿Quién sería capaz de decir 'no siento nada' con cara de sentirlo todo?",
      "¿Quién tendría más probabilidades de mandar un mensaje que debería quedarse en borrador?",
      "¿Quién convertiría un café en análisis sentimental completo?",
      "¿Quién elegiría mal con una constancia admirable?",
      "¿Quién se ilusionaría por una mínima muestra de atención?",
      "¿Quién sería el personaje principal de una comedia romántica desastrosa?"
    ]
  },
  {
    "id": "coche_transporte",
    "name": "Coche, transporte y caminos raros",
    "emoji": "🚗",
    "questions": [
      "¿Quién se marearía antes de salir del barrio?",
      "¿Quién elegiría la peor ruta con una seguridad preocupante?",
      "¿Quién pondría música y se convertiría en DJ tirano?",
      "¿Quién sería copiloto criticón sin saber llegar?",
      "¿Quién perdería el coche en un parking de dos plantas?",
      "¿Quién se equivocaría de andén con el billete en la mano?",
      "¿Quién llegaría al aeropuerto con tiempo de montar una tienda de campaña?",
      "¿Quién llegaría al aeropuerto con sudores y fe?",
      "¿Quién se dormiría en cualquier trayecto de más de siete minutos?",
      "¿Quién hablaría con el taxista como si fuera terapia?",
      "¿Quién se subiría al bus equivocado y lo llamaría aventura?",
      "¿Quién tendría más papeletas de olvidar dónde aparcó?",
      "¿Quién discutiría con el GPS como si fuese una persona?",
      "¿Quién llevaría snacks de viaje aunque sean diez minutos?",
      "¿Quién sería incapaz de viajar ligero?",
      "¿Quién haría paradas innecesarias por curiosidad?",
      "¿Quién perdería un tren por comprar algo en la estación?",
      "¿Quién tendría más miedo a perder el billete que a perder la dignidad?",
      "¿Quién se haría amigo de todos en un viaje largo?",
      "¿Quién reservaría asiento y acabaría sentado donde no es?",
      "¿Quién conduciría con playlists temáticas para cada carretera?",
      "¿Quién necesitaría mirar tres apps antes de moverse?",
      "¿Quién pediría indicaciones a alguien que parece más perdido que él?",
      "¿Quién convertiría una rotonda en crisis estratégica?",
      "¿Quién sería el que siempre pregunta '¿cuánto queda?'?",
      "¿Quién se bajaría en la parada equivocada por no preguntar?",
      "¿Quién prepararía el viaje como si fuese expedición polar?",
      "¿Quién tendría más probabilidades de llevar maleta al maletero equivocado?",
      "¿Quién cantaría todo el viaje aunque nadie lo apoye?",
      "¿Quién llegaría tarde incluso saliendo temprano?"
    ]
  },
  {
    "id": "animales_mascotas",
    "name": "Animales y mascotas",
    "emoji": "🐶",
    "questions": [
      "¿Quién hablaría con un perro usando voz de documental infantil?",
      "¿Quién sería dominado emocionalmente por un gato?",
      "¿Quién adoptaría un animal solo por una mirada triste?",
      "¿Quién pondría nombre humano a una mascota y lo defendería?",
      "¿Quién sería capaz de montar cumpleaños para su perro?",
      "¿Quién intentaría acariciar a un animal claramente antipático?",
      "¿Quién tendría más fotos de mascotas que de personas?",
      "¿Quién se disculparía con una paloma por espantarla?",
      "¿Quién dejaría que una mascota ocupe toda la cama?",
      "¿Quién sería el primero en llorar con un vídeo de rescate animal?",
      "¿Quién hablaría de su mascota como si fuera su jefe?",
      "¿Quién tendría más papeletas de perder una discusión con un gato?",
      "¿Quién intentaría entrenar a un animal y acabaría entrenado él?",
      "¿Quién se compraría ropa a juego con su mascota?",
      "¿Quién daría más datos de su perro que de su propia vida?",
      "¿Quién sería capaz de saludar antes al animal que al dueño?",
      "¿Quién se inventaría la voz interior de cada mascota?",
      "¿Quién tendría un animal imaginario de apoyo emocional?",
      "¿Quién se dejaría manipular por ojos de cachorrito?",
      "¿Quién compartiría comida aunque dijo que nunca lo haría?",
      "¿Quién sería capaz de organizar una sesión de fotos animal?",
      "¿Quién elegiría pareja según si le cae bien a su mascota?",
      "¿Quién pediría silencio porque el perro está durmiendo?",
      "¿Quién sospecharía que un gato le juzga con razón?",
      "¿Quién pondría más normas a las visitas que a la mascota?",
      "¿Quién sería capaz de hablar de animales en cualquier conversación?",
      "¿Quién tendría más probabilidades de rescatar un bicho de la calle?",
      "¿Quién llamaría bebé a un animal de 40 kilos?",
      "¿Quién se sentiría elegido si un gato se sienta cerca?",
      "¿Quién sería incapaz de decir no a una foto de cachorro?"
    ]
  },
  {
    "id": "musica_baile",
    "name": "Música y baile",
    "emoji": "🎵",
    "questions": [
      "¿Quién cantaría mal con una pasión que compensa todo?",
      "¿Quién se sabría canciones que nadie admite conocer?",
      "¿Quién bailaría primero y preguntaría después?",
      "¿Quién sería capaz de llorar con una canción de verbena?",
      "¿Quién pondría música para todos y acabaría poniéndola para sí mismo?",
      "¿Quién tendría la playlist más caótica del planeta?",
      "¿Quién haría air guitar con intensidad profesional?",
      "¿Quién se vendría arriba al escuchar una intro concreta?",
      "¿Quién interrumpiría una conversación porque 'esta parte es buenísima'?",
      "¿Quién desafinaría mirando a los ojos?",
      "¿Quién tendría una canción prohibida que siempre revive una historia?",
      "¿Quién sería capaz de bailar sentado?",
      "¿Quién haría coreografías de TikTok fuera de temporada?",
      "¿Quién se tomaría karaoke como declaración artística?",
      "¿Quién tendría más probabilidades de pedir una canción triste en un momento alegre?",
      "¿Quién cantaría el estribillo sin saber ninguna otra parte?",
      "¿Quién se inventaría la letra con seguridad criminal?",
      "¿Quién relacionaría cada canción con un ex, una época o un trauma menor?",
      "¿Quién sería DJ de coche insoportable?",
      "¿Quién bailaría sevillanas, reguetón o rock igual de raro?",
      "¿Quién necesitaría cerrar los ojos para cantar una balada?",
      "¿Quién gritaría 'temazo' antes de saber qué canción es?",
      "¿Quién se emocionaría al oír una canción de su infancia?",
      "¿Quién sería capaz de defender un gusto musical indefendible?",
      "¿Quién arruinaría una canción por ponerla demasiado?",
      "¿Quién inventaría pasos de baile con nombre propio?",
      "¿Quién tendría el momento musical más dramático de la noche?",
      "¿Quién bailaría mejor cuando nadie mira?",
      "¿Quién se pondría nostálgico con una canción cutre?",
      "¿Quién intentaría armonizar y crearía peligro acústico?"
    ]
  },
  {
    "id": "juegos_competitivos",
    "name": "Juegos y piques",
    "emoji": "🎲",
    "questions": [
      "¿Quién se enfadaría jugando a algo que dice que no le importa?",
      "¿Quién leería las reglas y aun así las entendería mal?",
      "¿Quién acusaría de trampa a alguien que simplemente juega mejor?",
      "¿Quién tendría más suerte y menos humildad?",
      "¿Quién sería capaz de romper una alianza en el último segundo?",
      "¿Quién negociaría como político en un juego de mesa?",
      "¿Quién se tomaría un UNO como conflicto diplomático?",
      "¿Quién fingiría no saber jugar y luego arrasaría?",
      "¿Quién se reiría demasiado al ganar?",
      "¿Quién perdería y diría que era partida de prueba?",
      "¿Quién inventaría una regla para beneficiarse?",
      "¿Quién sería el primero en pedir revancha inmediata?",
      "¿Quién guardaría rencor por una traición de juego?",
      "¿Quién tendría más probabilidades de distraer a todos para ganar?",
      "¿Quién haría equipo solo para culpar al compañero?",
      "¿Quién sería el más peligroso cuando empieza callado?",
      "¿Quién celebraría un punto como final mundial?",
      "¿Quién se quedaría pensando una jugada eterna y haría sufrir a todos?",
      "¿Quién tendría cara de no saber nada y estrategia secreta?",
      "¿Quién convertiría una derrota en injusticia histórica?",
      "¿Quién tendría más probabilidades de abandonar si va muy mal?",
      "¿Quién se aprendería las reglas para usar huecos legales?",
      "¿Quién jugaría con tal intensidad que asusta?",
      "¿Quién sería incapaz de farolear sin sonreír?",
      "¿Quién pactaría con todos y traicionaría a todos?",
      "¿Quién necesitaría narrar cada jugada?",
      "¿Quién se sentiría genio por ganar a niños?",
      "¿Quién sería el villano oficial de las partidas?",
      "¿Quién haría trampas tan mal que daría pena?",
      "¿Quién diría que no quiere jugar y acabaría más metido que nadie?"
    ]
  },
  {
    "id": "planes_cancelaciones",
    "name": "Planes y cancelaciones",
    "emoji": "📅",
    "questions": [
      "¿Quién propondría un plan y luego sería el primero en querer cancelarlo?",
      "¿Quién necesitaría saber parking, clima, menú y energía social antes de decir sí?",
      "¿Quién aceptaría un plan por presión y lo lamentaría al instante?",
      "¿Quién diría 'vamos viendo' como forma de vida?",
      "¿Quién sería capaz de cancelar con una excusa demasiado elaborada?",
      "¿Quién se apuntaría a todo y luego haría selección natural?",
      "¿Quién organizaría un plan con encuesta, mapa y presupuesto?",
      "¿Quién llegaría tarde al plan que él mismo creó?",
      "¿Quién necesitaría tres recordatorios para acordarse?",
      "¿Quién convertiría un café en jornada completa?",
      "¿Quién sería el primero en decir 'yo me voy pronto' y no irse?",
      "¿Quién buscaría excusas para volver a casa a las diez?",
      "¿Quién tendría más probabilidades de quedarse dormido antes de salir?",
      "¿Quién propondría un plan carísimo como si fuera normal?",
      "¿Quién se quejaría del plan pero sería quien más disfruta?",
      "¿Quién sería el rey de confirmar a última hora?",
      "¿Quién mandaría ubicación aunque todos sepan llegar?",
      "¿Quién preguntaría quién va antes de decidir si va?",
      "¿Quién tendría más miedo al FOMO que ganas reales?",
      "¿Quién haría un plan alternativo por si el primer plan tiene demasiada gente?",
      "¿Quién desaparecería del grupo justo cuando hay que decidir?",
      "¿Quién compraría entradas antes de preguntar a nadie?",
      "¿Quién se presentaría con alguien extra sin avisar?",
      "¿Quién intentaría cambiar el plan cinco minutos antes?",
      "¿Quién sería capaz de cancelar y luego arrepentirse al ver fotos?",
      "¿Quién tendría el talento de hacer planes imposibles?",
      "¿Quién diría 'yo me adapto' y luego pondría condiciones?",
      "¿Quién necesitaría siesta previa para un plan tranquilo?",
      "¿Quién llegaría con energía de festival a una merienda?",
      "¿Quién convertiría no hacer nada en el mejor plan?"
    ]
  },
  {
    "id": "emergencias_desastres",
    "name": "Emergencias cotidianas",
    "emoji": "🚨",
    "questions": [
      "¿Quién llamaría emergencia a quedarse sin café?",
      "¿Quién se bloquearía si pierde el cargador?",
      "¿Quién sería útil en una crisis real y desastre en una crisis tonta?",
      "¿Quién compraría velas para un apagón y olvidaría mechero?",
      "¿Quién intentaría arreglar algo y lo dejaría peor?",
      "¿Quién llamaría a tres personas antes de leer instrucciones?",
      "¿Quién improvisaría una solución con cinta adhesiva y fe?",
      "¿Quién se pondría dramático ante una gotera mínima?",
      "¿Quién organizaría evacuación por olor raro en la nevera?",
      "¿Quién perdería la calma porque alguien más perdió la calma?",
      "¿Quién sería el primero en buscar tutoriales?",
      "¿Quién tendría una caja de herramientas decorativa?",
      "¿Quién pediría ayuda con demasiada vergüenza y demasiado tarde?",
      "¿Quién solucionaría algo sin saber cómo y no podría repetirlo?",
      "¿Quién convertiría una avería en aventura vecinal?",
      "¿Quién sería capaz de guardar pilas gastadas durante años?",
      "¿Quién llamaría al seguro para preguntar algo absurdo?",
      "¿Quién se pondría chaleco imaginario de jefe de emergencias?",
      "¿Quién diría 'tranquilos' con voz de pánico?",
      "¿Quién resolvería una crisis con comida?",
      "¿Quién exageraría una picadura como si fuera documental médico?",
      "¿Quién se perdería buscando la salida de emergencia?",
      "¿Quién tendría linterna sin pilas?",
      "¿Quién sería el primero en hacer una lista de culpables?",
      "¿Quién se llevaría cosas inútiles en una evacuación ficticia?",
      "¿Quién llamaría a su madre antes que a un técnico?",
      "¿Quién sería capaz de abrir una puerta cerrada de la forma menos eficiente?",
      "¿Quién haría de portavoz oficial del caos?",
      "¿Quién se sentiría héroe por arreglar el WiFi reiniciándolo?",
      "¿Quién convertiría un pequeño susto en historia para cinco años?"
    ]
  },
  {
    "id": "secreto_inconfesable",
    "name": "Secretos inconfesables light",
    "emoji": "🤫",
    "questions": [
      "¿Quién tendría un gusto musical que oculta por supervivencia social?",
      "¿Quién ha buscado algo ridículo y borraría el historial con fuego?",
      "¿Quién tendría una obsesión rara que aún no ha contado?",
      "¿Quién se inventaría una vida paralela al pedir comida a domicilio?",
      "¿Quién tendría un crush famoso imposible y lo defendería?",
      "¿Quién repetiría una película mala demasiadas veces?",
      "¿Quién fingiría que no le gusta el cotilleo mientras pide detalles?",
      "¿Quién tendría más probabilidades de hablar con objetos cuando está solo?",
      "¿Quién guardaría capturas propias para reírse de sí mismo?",
      "¿Quién tendría una compra vergonzosa en el carrito desde hace meses?",
      "¿Quién se sabría letras de canciones que niega conocer?",
      "¿Quién tendría una manía de baño, cocina o sueño digna de estudio?",
      "¿Quién sería capaz de ensayar conversaciones en voz alta?",
      "¿Quién ha mirado el perfil de alguien que no debería demasiadas veces?",
      "¿Quién tendría más probabilidades de tener una nota del móvil titulada 'ideas raras'?",
      "¿Quién se emocionaría con algo que jamás admitiría públicamente?",
      "¿Quién tendría una superstición absurda que respeta por si acaso?",
      "¿Quién sería capaz de mentir sobre haber visto un clásico famoso?",
      "¿Quién escondería una afición porque el grupo se burlaría demasiado?",
      "¿Quién tendría una teoría secreta sobre todos los presentes?",
      "¿Quién se grabaría cantando y lo borraría de inmediato?",
      "¿Quién sería el primero en caer en un test de personalidad de internet?",
      "¿Quién tendría una conversación pendiente que nunca se atreve a abrir?",
      "¿Quién haría algo raro al estar solo y luego actuaría normal?",
      "¿Quién tendría una colección digital de memes demasiado específica?",
      "¿Quién miraría reseñas de productos que jamás va a comprar?",
      "¿Quién se inventaría una excusa para no reconocer que le da vergüenza?",
      "¿Quién tendría más probabilidades de escribir un mensaje y no mandarlo nunca?",
      "¿Quién guardaría un secreto ajeno mejor que uno propio?",
      "¿Quién sería el más fácil de pillar si intentara ocultar algo?"
    ]
  },
  {
    "id": "villanos_heroes",
    "name": "Héroes y villanos del grupo",
    "emoji": "🦹",
    "questions": [
      "¿Quién sería héroe por accidente y lo contaría toda la vida?",
      "¿Quién sería villano solo porque disfruta demasiado teniendo razón?",
      "¿Quién salvaría el día y luego pediría reconocimiento oficial?",
      "¿Quién traicionaría al grupo en una película por una razón ridícula?",
      "¿Quién tendría música de entrada al entrar en una sala?",
      "¿Quién sería mentor sabio con consejos que no aplica?",
      "¿Quién tendría un archienemigo sin que el otro lo sepa?",
      "¿Quién sería el personaje que parece secundario y roba la escena?",
      "¿Quién necesitaría capa para sentirse poderoso?",
      "¿Quién usaría un poder increíble para evitar hacer recados?",
      "¿Quién sería capaz de monologar antes de actuar?",
      "¿Quién tendría un lema absurdo pero pegadizo?",
      "¿Quién salvaría a todos y luego perdería las llaves?",
      "¿Quién sería el villano elegante que organiza bien los planes?",
      "¿Quién sería antihéroe por pereza?",
      "¿Quién tendría más probabilidades de cambiar de bando por comida?",
      "¿Quién daría discursos motivacionales demasiado largos?",
      "¿Quién sería el primero en apretar el botón rojo?",
      "¿Quién se sacrificaría dramáticamente por algo que no lo requiere?",
      "¿Quién sería el héroe local de una comunidad de vecinos?",
      "¿Quién tendría un escondite secreto lleno de snacks?",
      "¿Quién sería más peligroso con poder administrativo?",
      "¿Quién tendría un origen trágico por una tontería?",
      "¿Quién sería la mente maestra de un plan que no funciona?",
      "¿Quién sería el alivio cómico involuntario?",
      "¿Quién tendría más posibilidades de ganar por pura carisma?",
      "¿Quién sería capaz de dar una orden épica y tropezar?",
      "¿Quién sería el villano que todos acaban queriendo?",
      "¿Quién tendría una transformación final solo por cambiarse de chaqueta?",
      "¿Quién convertiría una misión sencilla en saga completa?"
    ]
  },
  {
    "id": "cultura_random",
    "name": "Cultura random",
    "emoji": "📚",
    "questions": [
      "¿Quién soltaría un dato inútil justo cuando nadie lo necesita?",
      "¿Quién ganaría un trivial por saber cosas que no dan dinero?",
      "¿Quién se inventaría un dato y lo diría con tanta seguridad que cuela?",
      "¿Quién corregiría una palabra y perdería amigos?",
      "¿Quién sería capaz de comparar cualquier situación con una película?",
      "¿Quién tendría opiniones muy fuertes sobre temas muy concretos?",
      "¿Quién leería la Wikipedia de algo raro a las dos de la mañana?",
      "¿Quién sería guía de museo insoportable sin haber estudiado nada?",
      "¿Quién se sentiría superior por conocer una palabra rara?",
      "¿Quién contaría el final de una serie sin darse cuenta?",
      "¿Quién sería capaz de recomendar un documental y luego no verlo?",
      "¿Quién haría una referencia que nadie entiende y se reiría solo?",
      "¿Quién convertiría una conversación normal en clase improvisada?",
      "¿Quién tendría más probabilidades de discutir sobre doblaje?",
      "¿Quién defendería una película mala como obra incomprendida?",
      "¿Quién sería el primero en decir 'el libro es mejor'?",
      "¿Quién memorizaría datos de canciones, fechas o actores sin querer?",
      "¿Quién usaría una cita famosa en el momento menos apropiado?",
      "¿Quién tendría una teoría sobre el final de cualquier cosa?",
      "¿Quién confundiría autores y lo defendería?",
      "¿Quién sería capaz de abrir un debate sobre una frase hecha?",
      "¿Quién tendría una lista de recomendaciones que nadie pidió?",
      "¿Quién se pondría intenso hablando de una serie vieja?",
      "¿Quién usaría cultura general como arma social?",
      "¿Quién se equivocaría en una respuesta fácil y acertaría una imposible?",
      "¿Quién tendría más probabilidades de saber capitales raras?",
      "¿Quién citaría una película en plena discusión seria?",
      "¿Quién haría spoilers de su propia vida?",
      "¿Quién tendría una colección mental de datos inútiles pero brillantes?",
      "¿Quién se sentiría insultado si no conoces su película favorita?"
    ]
  },
  {
    "id": "energia_caotica",
    "name": "Energía caótica",
    "emoji": "⚡",
    "questions": [
      "¿Quién entraría en una habitación y cambiaría el clima emocional?",
      "¿Quién empezaría una frase normal y terminaría organizando una revolución?",
      "¿Quién tiene más energía de personaje secundario que roba la escena?",
      "¿Quién sería capaz de convertir un silencio en espectáculo?",
      "¿Quién se apunta a lo que sea si suena mínimamente peligroso?",
      "¿Quién diría 'tengo una idea' y todos deberían preocuparse?",
      "¿Quién haría reír a alguien en el peor momento posible?",
      "¿Quién no sabe entrar discretamente en ningún sitio?",
      "¿Quién sería capaz de hacer tres planes simultáneos y fallar en todos?",
      "¿Quién tiene más probabilidades de iniciar una ovación sin motivo?",
      "¿Quién sería el motor emocional de una noche descontrolada?",
      "¿Quién haría una apuesta absurda y la cumpliría?",
      "¿Quién se convertiría en líder de una fila sin querer?",
      "¿Quién diría 'no pasa nada' justo antes de que pase todo?",
      "¿Quién tendría más peligro con una idea y público?",
      "¿Quién sería capaz de animar a una piedra?",
      "¿Quién empezaría bailando y acabaría dando consejos legales?",
      "¿Quién haría algo por la anécdota aunque sea mala idea?",
      "¿Quién tendría más probabilidades de gritar una frase memorable?",
      "¿Quién convertiría una espera aburrida en concurso improvisado?",
      "¿Quién se vendría arriba con el mínimo apoyo?",
      "¿Quién tiene más energía de 'esto va a acabar raro'?",
      "¿Quién sería capaz de arrastrar al grupo a una misión absurda?",
      "¿Quién no necesita alcohol para dar miedo social?",
      "¿Quién confundiría espontaneidad con incendio controlado?",
      "¿Quién sería el primero en probar algo sin leer instrucciones?",
      "¿Quién tendría más probabilidades de hacer una entrada dramática?",
      "¿Quién empezaría una moda ridícula en el grupo?",
      "¿Quién sería el caos, pero un caos útil?",
      "¿Quién terminaría siendo la razón por la que hay nuevas normas?"
    ]
  }
];

const questions = questionCategories.flatMap(category =>
  category.questions.map(question => ({
    id: `${category.id}-${question.slice(0, 24).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
    categoryId: category.id,
    categoryName: category.name,
    text: question,
  }))
);

window.questionCategories = questionCategories;
window.questions = questions;
