const questionCategories = [
  {
    id: "fiesta",
    name: "Fiesta y noche",
    emoji: "🎉",
    questions: [
      "¿Quién sería el primero en proponer una última copa cuando ya no puede más?",
      "¿Quién acabaría cantando encima de una mesa?",
      "¿Quién se haría amigo del camarero en cinco minutos?",
      "¿Quién desaparecería de fiesta y volvería con una historia imposible?",
      "¿Quién pediría una canción al DJ sin ninguna vergüenza?",
      "¿Quién sería el primero en perder la chaqueta?",
      "¿Quién convertiría una cena tranquila en una noche legendaria?",
      "¿Quién se inventaría pasos de baile y los defendería como si fueran profesionales?",
      "¿Quién acabaría hablando con desconocidos como si fueran amigos de toda la vida?",
      "¿Quién diría que se va pronto y sería el último en volver?",
      "¿Quién organizaría una fiesta improvisada en cualquier sitio?",
      "¿Quién se sabría todas las canciones antiguas de una verbena?",
      "¿Quién sería el peor eligiendo el sitio para salir?",
      "¿Quién animaría a todo el grupo aunque nadie tuviera ganas?",
      "¿Quién perdería la voz antes de medianoche?",
      "¿Quién pediría comida a las cuatro de la mañana como si fuera una emergencia?",
      "¿Quién acabaría con confeti en el pelo sin saber de dónde salió?",
      "¿Quién haría un brindis demasiado intenso?",
      "¿Quién sería el encargado oficial de las fotos borrosas?",
      "¿Quién convertiría cualquier cumpleaños en una boda gitana?"
    ]
  },
  {
    id: "amistad",
    name: "Amistad y grupo",
    emoji: "🤝",
    questions: [
      "¿Quién sería el primero en montar un grupo de WhatsApp para algo innecesario?",
      "¿Quién contaría una anécdota del grupo exagerándola un 300%?",
      "¿Quién sería el pacificador oficial después de una discusión tonta?",
      "¿Quién llegaría tarde incluso si la quedada fuera en su casa?",
      "¿Quién se olvidaría de responder pero juraría que lo leyó mentalmente?",
      "¿Quién se apuntaría a un plan sin mirar ni fecha ni sitio?",
      "¿Quién sería el mejor preparando una sorpresa para el grupo?",
      "¿Quién guardaría un secreto durante años?",
      "¿Quién soltaría un secreto sin darse cuenta en el peor momento?",
      "¿Quién haría de guía turístico aunque no conociera la ciudad?",
      "¿Quién sería el más probable en llegar con un amigo nuevo que nadie conoce?",
      "¿Quién pondría paz y a los dos minutos volvería a liarla?",
      "¿Quién organizaría una quedada y luego no iría?",
      "¿Quién tiene más papeletas para convertirse en meme del grupo?",
      "¿Quién defendería a sus amigos aunque no tuvieran razón?",
      "¿Quién sería el que siempre pide captura para entender el drama?",
      "¿Quién se acordaría de todos los cumpleaños?",
      "¿Quién regalaría algo absurdo pero perfecto?",
      "¿Quién sería el más fácil de convencer para un plan loco?",
      "¿Quién necesitaría tres audios de dos minutos para decir que sí?"
    ]
  },
  {
    id: "redes",
    name: "Redes y tecnología",
    emoji: "📱",
    questions: [
      "¿Quién subiría una historia y se arrepentiría a los diez minutos?",
      "¿Quién tendría el historial de búsqueda más difícil de explicar?",
      "¿Quién pediría ayuda porque el móvil está en silencio?",
      "¿Quién sería influencer por accidente?",
      "¿Quién contestaría un mensaje importante tres días tarde?",
      "¿Quién haría una foto a la comida antes de probarla?",
      "¿Quién tendría 37 pestañas abiertas y ninguna útil?",
      "¿Quién caería antes en una oferta demasiado buena para ser verdad?",
      "¿Quién enviaría un audio eterno para contar algo mínimo?",
      "¿Quién perdería una discusión por mandar un sticker equivocado?",
      "¿Quién se compraría un gadget raro y lo defendería como imprescindible?",
      "¿Quién usaría IA para escribir una disculpa?",
      "¿Quién sería capaz de hacerse viral por una tontería?",
      "¿Quién tendría más fotos repetidas en la galería?",
      "¿Quién se pondría nervioso si se queda sin batería?",
      "¿Quién contestaría con memes a una conversación seria?",
      "¿Quién tendría el móvil más roto pero seguiría diciendo que funciona?",
      "¿Quién grabaría un tutorial sin saber hacer lo que explica?",
      "¿Quién sería el primero en probar una app nueva y abandonarla al día siguiente?",
      "¿Quién se equivocaría de chat justo en el peor momento?"
    ]
  },
  {
    id: "trabajo",
    name: "Trabajo y responsabilidades",
    emoji: "💼",
    questions: [
      "¿Quién sobreviviría mejor a una reunión que no acaba nunca?",
      "¿Quién mandaría un correo demasiado formal para pedir algo sencillo?",
      "¿Quién sería el jefe más caótico?",
      "¿Quién se ofrecería voluntario y luego se arrepentiría?",
      "¿Quién haría una presentación con efectos innecesarios?",
      "¿Quién llegaría al trabajo con una excusa elaboradísima?",
      "¿Quién sería el primero en montar una empresa por impulso?",
      "¿Quién fingiría entender una explicación técnica hasta el final?",
      "¿Quién tendría el escritorio más desordenado?",
      "¿Quién haría una pausa de café que se convierte en excursión?",
      "¿Quién sería el peor ocultando que no ha preparado nada?",
      "¿Quién acabaría liderando un proyecto sin saber cómo?",
      "¿Quién pondría nombres épicos a tareas aburridas?",
      "¿Quién se tomaría demasiado en serio un juego de team building?",
      "¿Quién sería incapaz de decir no a un favor?",
      "¿Quién dejaría todo perfecto justo cinco minutos antes de entregarlo?",
      "¿Quién convertiría una tarea simple en una investigación completa?",
      "¿Quién se bloquearía por tener demasiadas opciones?",
      "¿Quién sería el empleado del mes y aun así se quejaría?",
      "¿Quién llevaría snacks para todos y ganaría la oficina?"
    ]
  },
  {
    id: "viajes",
    name: "Viajes y aventuras",
    emoji: "✈️",
    questions: [
      "¿Quién se perdería usando el GPS?",
      "¿Quién haría una maleta gigante para una noche?",
      "¿Quién intentaría hablar otro idioma con acento inventado?",
      "¿Quién planificaría cada minuto del viaje en una hoja de cálculo?",
      "¿Quién perdería el billete justo antes de entrar?",
      "¿Quién se haría amigo de alguien local el primer día?",
      "¿Quién elegiría restaurante solo por las fotos?",
      "¿Quién acabaría comprando un recuerdo absurdo?",
      "¿Quién dormiría durante todo el trayecto y despertaría fresco?",
      "¿Quién se quemaría el primer día de playa aunque hubiera sombra?",
      "¿Quién pediría indicaciones y entendería lo contrario?",
      "¿Quién convertiría una escapada barata en un gasto enorme?",
      "¿Quién haría cola para una atracción sin saber qué es?",
      "¿Quién perdería al grupo en un mercado?",
      "¿Quién haría 200 fotos de una misma fachada?",
      "¿Quién se enamoraría de una ciudad en diez minutos?",
      "¿Quién sería el guía del viaje aunque nadie se lo pidió?",
      "¿Quién olvidaría el cargador en el hotel?",
      "¿Quién acabaría comiendo lo más raro del menú?",
      "¿Quién diría que controla el mapa y llevaría a todos en círculos?"
    ]
  },
  {
    id: "supervivencia",
    name: "Supervivencia y caos",
    emoji: "🧟",
    questions: [
      "¿Quién sería el primero en morir en un apocalipsis zombie?",
      "¿Quién sobreviviría más tiempo solo en una isla desierta?",
      "¿Quién se haría líder del refugio sin que nadie le votara?",
      "¿Quién gastaría todos los recursos el primer día?",
      "¿Quién intentaría domesticar a un animal salvaje?",
      "¿Quién sería el encargado de vigilar y se quedaría dormido?",
      "¿Quién inventaría una herramienta inútil pero con orgullo?",
      "¿Quién tendría más posibilidades de encontrar comida por casualidad?",
      "¿Quién se asustaría de su propia sombra?",
      "¿Quién haría un plan perfecto y luego no lo seguiría?",
      "¿Quién negociaría con los zombies si pudiera?",
      "¿Quién convertiría el búnker en una comunidad organizada?",
      "¿Quién se perdería buscando ayuda?",
      "¿Quién contaría chistes en el peor momento posible?",
      "¿Quién sería el primero en hacer una bandera para el campamento?",
      "¿Quién intentaría resolverlo todo viendo tutoriales?",
      "¿Quién guardaría provisiones secretas?",
      "¿Quién se haría famoso después del desastre?",
      "¿Quién sería el más peligroso con una linterna?",
      "¿Quién diría 'yo sé hacer fuego' y no sabría?"
    ]
  },
  {
    id: "amor",
    name: "Amor y drama",
    emoji: "💘",
    questions: [
      "¿Quién se enamoraría de alguien por cómo escribe los mensajes?",
      "¿Quién prepararía una cita demasiado intensa para ser primera cita?",
      "¿Quién stalkearía perfiles antiguos y acabaría dando like sin querer?",
      "¿Quién perdonaría demasiado rápido?",
      "¿Quién montaría una película mental por un mensaje corto?",
      "¿Quién sería el mejor dando consejos amorosos que nunca aplica?",
      "¿Quién se pondría nervioso con un silencio de cinco minutos?",
      "¿Quién escribiría y borraría el mismo mensaje veinte veces?",
      "¿Quién acabaría siendo cupido del grupo?",
      "¿Quién se fijaría antes en alguien completamente incompatible?",
      "¿Quién haría una playlist para superar algo que duró dos semanas?",
      "¿Quién tendría más probabilidades de volver con su ex?",
      "¿Quién sería el más dramático viendo una comedia romántica?",
      "¿Quién confundiría amabilidad con señales clarísimas?",
      "¿Quién intentaría ligar contando una anécdota larguísima?",
      "¿Quién recordaría una conversación exacta de hace años?",
      "¿Quién tendría una cita perfecta y aun así encontraría un problema?",
      "¿Quién sería capaz de escribir una carta de amor en 2026?",
      "¿Quién pediría consejo al grupo y haría lo contrario?",
      "¿Quién se enamoraría durante unas vacaciones?"
    ]
  },
  {
    id: "dinero",
    name: "Dinero y compras",
    emoji: "💸",
    questions: [
      "¿Quién gastaría su sueldo entero el primer día?",
      "¿Quién compraría algo solo porque estaba rebajado?",
      "¿Quién sería el peor gestionando una economía familiar?",
      "¿Quién tendría una suscripción que no recuerda haber contratado?",
      "¿Quién encontraría siempre una excusa para pedir comida a domicilio?",
      "¿Quién se haría rico con una idea absurda?",
      "¿Quién guardaría tickets de hace cinco años?",
      "¿Quién prestaría dinero y le daría vergüenza pedirlo de vuelta?",
      "¿Quién compraría el regalo más caro para demostrar cariño?",
      "¿Quién negociaría hasta en una máquina expendedora?",
      "¿Quién se arrepentiría justo después de pagar?",
      "¿Quién caería en una compra impulsiva a medianoche?",
      "¿Quién viviría feliz con una hoja de gastos perfectamente ordenada?",
      "¿Quién sería capaz de montar un negocio de algo rarísimo?",
      "¿Quién perdería dinero por no leer la letra pequeña?",
      "¿Quién usaría cupones con orgullo absoluto?",
      "¿Quién pediría la cuenta y haría matemáticas imposibles?",
      "¿Quién invitaría y luego se quejaría del precio?",
      "¿Quién ahorraría para algo serio y acabaría comprando una tontería?",
      "¿Quién tendría más monedas sueltas en todos los bolsillos?"
    ]
  },
  {
    id: "casa",
    name: "Casa y convivencia",
    emoji: "🏠",
    questions: [
      "¿Quién dejaría una taza en cualquier habitación?",
      "¿Quién sería el vecino más cotilla?",
      "¿Quién convertiría ordenar la casa en una misión épica?",
      "¿Quién compraría plantas y olvidaría regarlas?",
      "¿Quién tendría una silla llena de ropa con historia propia?",
      "¿Quién sería el peor eligiendo decoración?",
      "¿Quién se tomaría demasiado en serio una barbacoa?",
      "¿Quién montaría un mueble y le sobrarían piezas?",
      "¿Quién tendría más probabilidades de perder las llaves dentro de casa?",
      "¿Quién haría limpieza general y acabaría mirando recuerdos antiguos?",
      "¿Quién sería el que nunca cambia el rollo de papel?",
      "¿Quién tendría la nevera más misteriosa?",
      "¿Quién pondría una alarma para sacar la basura y la ignoraría?",
      "¿Quién sería el mejor anfitrión?",
      "¿Quién quemaría unas tostadas y diría que están perfectas?",
      "¿Quién se mudaría con demasiadas cajas de cosas inútiles?",
      "¿Quién discutiría con un electrodoméstico?",
      "¿Quién tendría el cajón del caos más impresionante?",
      "¿Quién prepararía la casa como si viniera la reina?",
      "¿Quién sería incapaz de tirar una caja 'por si acaso'?"
    ]
  },
  {
    id: "absurdo",
    name: "Absurdo total",
    emoji: "🌀",
    questions: [
      "¿Quién sería elegido alcalde de una isla llena de patos?",
      "¿Quién discutiría con una estatua porque le mira raro?",
      "¿Quién sobreviviría a base de bocadillos y optimismo?",
      "¿Quién abriría un museo dedicado a sus propios fracasos?",
      "¿Quién sería capaz de perder una carrera contra una tortuga?",
      "¿Quién pondría nombre a todos los objetos de su casa?",
      "¿Quién inventaría una religión alrededor de una croqueta?",
      "¿Quién sería el villano más adorable de una película?",
      "¿Quién intentaría enseñar trucos a una piedra?",
      "¿Quién ganaría un concurso de excusas ridículas?",
      "¿Quién haría una rueda de prensa para explicar un malentendido tonto?",
      "¿Quién se convertiría en leyenda local por accidente?",
      "¿Quién tendría una pelea épica con una puerta automática?",
      "¿Quién sería el protagonista de un anuncio rarísimo?",
      "¿Quién se perdería en una tienda pequeña?",
      "¿Quién defendería una teoría absurda con datos inventados?",
      "¿Quién sería arrestado por exceso de entusiasmo?",
      "¿Quién lloraría viendo un anuncio de detergente?",
      "¿Quién podría hacerse famoso por caerse con estilo?",
      "¿Quién convertiría una partida de parchís en una cuestión de honor?"
    ]
  },
  {
    id: "pueblo",
    name: "Pueblo y familia",
    emoji: "🌄",
    questions: [
      "¿Quién sería el primero en apuntarse a una verbena de pueblo?",
      "¿Quién conocería a todo el mundo aunque diga que no conoce a nadie?",
      "¿Quién sería el encargado de contar los chismes familiares?",
      "¿Quién discutiría por la mejor forma de hacer una tortilla?",
      "¿Quién acabaría bailando con una señora desconocida?",
      "¿Quién se sabría todas las fiestas patronales de memoria?",
      "¿Quién se tomaría muy en serio una competición de peñas?",
      "¿Quién llegaría a comer y se quedaría hasta cenar?",
      "¿Quién sería el rey o reina de la sobremesa?",
      "¿Quién se llevaría comida para tres días después de una visita familiar?",
      "¿Quién se pondría sentimental con una canción antigua?",
      "¿Quién acabaría organizando un campeonato improvisado?",
      "¿Quién tendría más papeletas de salir en una foto del periódico local?",
      "¿Quién preguntaría '¿y este de quién es?' en cada reunión?",
      "¿Quién sería el primero en sacar una silla a la puerta?",
      "¿Quién defendería su pueblo como si fuera capital del mundo?",
      "¿Quién sería el pregonero perfecto?",
      "¿Quién haría una ruta gastronómica sin salir de la plaza?",
      "¿Quién llevaría postre aunque nadie se lo pidió?",
      "¿Quién tendría una anécdota con cada persona del pueblo?"
    ]
  },
  {
    id: "personalidad",
    name: "Personalidad y manías",
    emoji: "🧠",
    questions: [
      "¿Quién necesita más validación en redes sociales?",
      "¿Quién se pondría competitivo con cualquier tontería?",
      "¿Quién tiene más probabilidades de cambiar de opinión en cinco minutos?",
      "¿Quién sería el más dramático por algo pequeño?",
      "¿Quién intentaría parecer tranquilo estando completamente nervioso?",
      "¿Quién sería el mejor mintiendo en una entrevista de trabajo?",
      "¿Quién dormiría más horas al día si pudiera?",
      "¿Quién sería incapaz de ver una notificación sin abrirla?",
      "¿Quién empezaría un hobby nuevo cada mes?",
      "¿Quién se obsesionaría con una canción hasta quemarla?",
      "¿Quién tiene más probabilidades de hablar solo en voz alta?",
      "¿Quién sería el más testarudo en una discusión absurda?",
      "¿Quién se motivaría a las doce de la noche para cambiar su vida?",
      "¿Quién sería el primero en abandonar una dieta?",
      "¿Quién tiene más cara de no haber hecho nada y haberlo hecho todo?",
      "¿Quién pediría perdón aunque no tenga culpa?",
      "¿Quién sería el más fácil de asustar?",
      "¿Quién tendría un plan B, C y D para ir a comprar pan?",
      "¿Quién sería el más peligroso jugando con confianza?",
      "¿Quién convertiría una pequeña victoria en celebración nacional?"
    ]
  }
];

const questions = questionCategories.flatMap(category =>
  category.questions.map(question => ({
    id: `${category.id}-${question.slice(0, 24).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`,
    categoryId: category.id,
    categoryName: category.name,
    text: question,
  }))
);

window.questionCategories = questionCategories;
window.questions = questions;
