const questions = [
  "¿Quién sería el primero en morir en un apocalipsis zombie?",
  "¿Quién vendería a sus amigos por dinero?",
  "¿Quién lloraría en una peli de Disney?",
  "¿Quién se perdería en su propio barrio?",
  "¿Quién envejecerá mejor?",
  "¿Quién tiene más probabilidades de hacerse famoso?",
  "¿Quién es el más tóxico en una discusión?",
  "¿Quién sería el peor jefe?",
  "¿Quién mentiría mejor en una entrevista de trabajo?",
  "¿Quién sobreviviría más tiempo solo en una isla desierta?",
  "¿Quién gastaría su sueldo entero el primer día?",
  "¿Quién tiene más probabilidades de ir a la cárcel?",
  "¿Quién olvidaría su propio cumpleaños?",
  "¿Quién sería el primero en rendirse en un reality show?",
  "¿Quién tiene el historial de WhatsApp más comprometedor?",
  "¿Quién sería el líder de una secta?",
  "¿Quién es el más propenso a irse de la lengua con un secreto?",
  "¿Quién dormiría más horas al día si pudiera?",
  "¿Quién necesita más validación en redes sociales?",
  "¿Quién seria el más aterrador en modo borracho?",
];
